/**
 * components/admin/settings/DevToolsRow.tsx (M12.2 B1 Task 8.3)
 *
 * The "Preferences"-area dev-tools entry on the admin settings page. It is
 * gated on the BUILD-TIME `DEV_PANEL_PRESENT` constant (generated by
 * scripts/with-admin-dev-flag.mjs and committed `false`), NOT on the runtime
 * `process.env.ADMIN_DEV_PANEL_ENABLED`. Keying off runtime env would render a
 * link to an absent /admin/dev 404 route in a prod build whose runtime env
 * flips true (the M3 build-vs-runtime class). In normal builds the constant is
 * false and this component renders nothing, so the page is visually unchanged.
 */
import Link from "next/link";
import { DEV_PANEL_PRESENT } from "@/lib/admin/__generated__/devPanelPresent";

export function DevToolsRow() {
  if (!DEV_PANEL_PRESENT) return null;
  return (
    <section
      data-testid="admin-dev-tools-row"
      className="flex flex-wrap items-center justify-between gap-3 rounded-md border border-border bg-surface p-tile-pad"
    >
      <div className="min-w-0">
        <h3 className="text-lg font-semibold text-text-strong">
          Developer tools
        </h3>
        <p className="max-w-prose text-sm text-text-subtle">
          Fixture tester and parse diagnostics. Hidden from normal use.
        </p>
      </div>
      <Link
        href="/admin/dev"
        data-testid="admin-dev-tools-open"
        className="inline-flex min-h-tap-min items-center justify-center rounded-sm border border-border-strong bg-bg px-4 text-base font-medium text-text-strong hover:bg-surface-sunken focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus-ring"
      >
        Open
      </Link>
    </section>
  );
}
