// @generated by scripts/generate-execution-methods.ts; do not edit. Regenerate: pnpm gen:execution-methods
// Source: node_modules/postgres/types/index.d.ts (postgres 3.4.9).
export const POSTGRES_TYPES_VERSION = "3.4.9";
export const POSTGRES_EXECUTION_CORE: readonly string[] = ["file","listen","notify","unsafe"];
export const POSTGRES_PARAMETER_MEMBERS: readonly string[] = ["array","json"];
