// Single source of truth for the vitest two-project partition (imported by both
// vitest.config.ts and tests/cross-cutting/vitest-projects-partition.test.ts).
// Kept in its own module so vitest.config.ts has a default export only (avoids
// rollup's MIXED_EXPORTS warning when the config is bundled).
//
// The PARALLEL project: directories whose test files were empirically verified
// to be DB-free and fixture-corpus-safe (each passed with every Supabase/DB
// endpoint pointed at a closed port, run with fileParallelism:true). These run
// concurrently. EVERYTHING ELSE runs in the SERIAL project (fileParallelism:
// false) because it shares mutable global state — the local Supabase DB
// (tests/db, tests/admin, tests/api, tests/sync, tests/onboarding, …) or the
// fixtures/shows/raw corpus WRITER (tests/sync/dev-routing — the corpus
// READERS in tests/parser moved to the parallel project in Phase 2, 2026-07-19;
// phases never overlap, so readers never race the serial writer). vitest runs
// the two projects in SEPARATE sequential phases, so the parallel project
// never overlaps the serial one — a fixture-corpus reader in the parallel set
// (e.g. tests/help/fixture-range-parser, tests/parser) never races the serial
// writer. New directories default to SERIAL (safe): add to this list ONLY after
// verifying the dir is DB-free.
//
// The DB-free claim is now CI-ENFORCED rather than trusted. It began as a
// one-time, per-DIRECTORY audit (2026-06-23), so files added to these dirs
// afterwards inherited it unverified -- two had, and were racing each other
// against one shared DB under fileParallelism:true (CI probe run 29758568301;
// both moved to tests/admin/). The unit-suite-nodb job now runs this ENTIRE
// project on a runner with no Supabase and no psql installed, on every PR, so a
// DB-touching file added to a parallel dir fails immediately instead of drifting
// in silently. Spec: docs/superpowers/specs/ci/2026-07-20-unit-suite-project-split.md
//
// The vitest-projects-partition meta-test pins the
// invariant that every non-nightly test file lands in exactly one default
// project (the nightly mutation-harness files land in none by design).

export const BASE_INCLUDE = ["tests/**/*.test.ts", "tests/**/*.test.tsx"];

// Files the unit-suite CI job must NOT run (each needs an environment the
// local-bootstrap runner can't provide, or starves under full-suite concurrency
// on the 2-core runner). They live in SERIAL dirs and run normally for local
// `pnpm test` and — crucially — for the x-audits jobs that invoke them DIRECTLY
// via `vitest run <file>` (x5 → email-canonicalization). So they must NOT be in
// the always-on project `exclude` (that would make those targeted audits run 0
// tests). Instead the config adds them to the serial project's exclude ONLY when
// `VITEST_EXCLUDE_ENV_BOUND=1` (set by unit-suite.yml). A plain project-level
// exclude is required because vitest IGNORES the CLI `--exclude` flag when a
// project already defines its own `exclude` (the bug that broke the first run of
// this split — the CLI flags silently did nothing and email-canonicalization
// ran + timed out).
export const ENV_BOUND_EXCLUDES = [
  "**/tests/admin/test-auth-gate.test.ts",
  "**/tests/cross-cutting/pg-cron-coverage.test.ts",
  "**/tests/cross-cutting/email-canonicalization.test.ts",
];

// The mutation harness (8 LPT shard files + 1 gates file, tests/parser/
// mutationHarness.*.test.ts — sharding spec §3.3/§3.4) exhaustively parses ~102k
// mutants — far past any merge-gating leg budget. The files live in NO default
// project: the serial project excludes them UNCONDITIONALLY, and a third
// `mutation` project (fileParallelism:true — the sharding speedup) exists ONLY
// when VITEST_INCLUDE_MUTATION_HARNESS=1 (nightly workflow + local regen runs).
// (User-directed nightly placement 2026-07-06; parent spec §Non-goals + AC-5.)
export const MUTATION_TEST_GLOBS = ["tests/parser/mutationHarness.*.test.ts"];
export const NIGHTLY_ONLY_EXCLUDES = ["**/tests/parser/mutationHarness.*.test.ts"];

// Files that live in a SERIAL directory but are empirically DB-FREE and
// parallel-safe, so they run in the parallel project instead.
//
// The serial project is the DEFAULT bucket -- a file lands there because of its
// directory, not because it needs a database. Measurement showed most of it does
// not: 556 of 772 serial files pass with NO database AND fileParallelism:true.
// They were paying a ~71s Supabase boot and one-file-at-a-time execution for
// nothing.
//
// PROVENANCE -- this list is measured, not curated. Two CI runs, identical
// commands, one with a database and one on a runner with none installed:
//   no-DB   run 29765228945
//   with-DB run 29765796899 (control)
// A file qualifies ONLY if it passed in BOTH runs with an IDENTICAL, non-zero
// count of passing assertions.
//
// The control is what makes this trustworthy, and it disqualified 71 files that
// the naive test would have moved:
//   - 66 files passed without a database while executing ZERO tests -- they SKIP
//     when no DB is reachable (e.g. *.db.test.ts, *real-db.test.ts)
//   - 5 files silently ran FEWER assertions without a database while still
//     reporting green: wizard-approve-route 6 -> 2, wizard-unapprove-route 6 -> 3,
//     unignore-route 6 -> 3, resolveBlocker 19 -> 11, qualityRegressionLifecycle
//     21 -> 16
// "Passed without a database" is therefore NOT evidence a file is DB-free. Never
// extend this list by hand or by grep -- re-run both probes and compare counts.
//
// Directories stay SERIAL by default (the safe default is unchanged): a new file
// added to any of these dirs runs serially until it is measured. Only exact paths
// listed here move.
//
// ONE measured-movable file is deliberately NOT here: no-global-cursor.test.ts.
// It is the heaviest file in the suite (54s) and CPU-bound -- a doc scan, not a DB
// test -- so under fileParallelism it competes with the other workers and blew the
// 120s testTimeout locally. Same class as email-canonicalization, which is already
// excluded for starving under concurrency. It is DB-free, but "DB-free" is not the
// only criterion; it stays serial where it gets a core to itself. Its 54s is also
// the floor on any DB leg, so moving it would not have shortened the critical path.
export const MEASURED_MOVABLE_BUT_HELD_SERIAL = ["tests/cross-cutting/no-global-cursor.test.ts"];
export const PARALLEL_DB_FREE_FILES = [
  "tests/admin/_metaAttentionRoutes.test.ts",
  "tests/admin/_metaBoundedReads.test.ts",
  "tests/admin/_metaInfraContract.test.ts",
  "tests/admin/_metaManualResolveRegistry.test.ts",
  "tests/admin/_showReviewReadPathPin.test.ts",
  "tests/admin/adminAlertsGlobalResolve.test.ts",
  "tests/admin/adminAlertsShowScopedResolve.test.ts",
  "tests/admin/admins-actions.test.ts",
  "tests/admin/attentionItems.test.ts",
  "tests/admin/autoAppliedActions.test.ts",
  "tests/admin/bellAudience.test.ts",
  "tests/admin/bellFeed.test.ts",
  "tests/admin/bellTriage.test.ts",
  "tests/admin/bellValidation.test.ts",
  "tests/admin/crewLinkMailto.test.ts",
  "tests/admin/dev-requires-developer.test.ts",
  "tests/admin/dev-route-prod-classification.test.ts",
  "tests/admin/devPanelPresent.test.ts",
  "tests/admin/devSpecNonEmpty.test.ts",
  "tests/admin/driveConnectionHealth.test.ts",
  "tests/admin/embeddedAdminEmails.test.ts",
  "tests/admin/feedTelemetry.test.tsx",
  "tests/admin/fetchDashboardData-archived.test.ts",
  "tests/admin/fetchDashboardData.test.ts",
  "tests/admin/healthAlerts.test.ts",
  "tests/admin/healthResolveGuard.test.ts",
  "tests/admin/healthRollup.test.ts",
  "tests/admin/ignoredSheetsView.test.tsx",
  "tests/admin/loadAlertSummary.test.ts",
  "tests/admin/loadAppEvents.test.ts",
  "tests/admin/loadCronHealth.test.ts",
  "tests/admin/loadIgnoredWarnings.test.ts",
  "tests/admin/loadNeedsAttention.test.ts",
  "tests/admin/loadRecentAutoApplied.test.ts",
  "tests/admin/loadTelemetryStats.test.ts",
  "tests/admin/mapRoleTokenAction.test.ts",
  "tests/admin/mapRoleTokenStagedAction.test.ts",
  "tests/admin/needsAttention.test.ts",
  "tests/admin/needsAttentionCount.parallel.test.ts",
  "tests/admin/needsAttentionCount.test.ts",
  "tests/admin/needsAttentionSyncProblem.test.ts",
  "tests/admin/no-inline-email-normalization.test.ts",
  "tests/admin/notify-toggle-actions.test.ts",
  "tests/admin/onboardingNavSuppression.test.tsx",
  "tests/admin/parseAppEventFilters.test.ts",
  "tests/admin/pendingIngestionsLiveActions.test.ts",
  "tests/admin/perShowActionableKeyStability.test.tsx",
  "tests/admin/perShowActionableRenderControls.test.tsx",
  "tests/admin/perShowDataQualityActionable.test.tsx",
  "tests/admin/pickerResetControl.test.tsx",
  "tests/admin/publishIntent.test.ts",
  "tests/admin/rawUnrecognized.test.ts",
  "tests/admin/readShowReviewSnapshot.test.ts",
  "tests/admin/reap-developer-gate.test.ts",
  "tests/admin/resolveAlert.test.ts",
  "tests/admin/resolveAutoCodeGuard.test.ts",
  "tests/admin/resolveHealthAlert.test.ts",
  "tests/admin/retryWatchAction.test.ts",
  "tests/admin/roleFlagsNoticeReclassify.test.ts",
  "tests/admin/roleTokenMappingsSettingsActions.test.ts",
  "tests/admin/serverNoClientValueCall.test.ts",
  "tests/admin/setStagedUseRawDecisionAction.test.ts",
  "tests/admin/setUseRawDecisionAction.test.ts",
  "tests/admin/showFeedAcceptActions.test.ts",
  "tests/admin/showPageFeed.test.tsx",
  "tests/admin/stagedDiagramGuards.test.ts",
  "tests/admin/step3Buckets.test.ts",
  "tests/admin/step3DeletionSafety.test.ts",
  "tests/admin/step3DisplayState.test.ts",
  "tests/admin/step3ReviewItemTiers.test.ts",
  "tests/admin/step3SectionStatus.test.ts",
  "tests/admin/step3UnifiedRead.test.ts",
  "tests/admin/syncStatus.test.ts",
  "tests/admin/telemetry-requires-developer.test.ts",
  "tests/admin/telemetryFilterHref.test.ts",
  "tests/admin/telemetryRouteAudit.test.ts",
  "tests/admin/upsertAdminAlert.test.ts",
  "tests/admin/validationDeployment.test.ts",
  "tests/admin/validationReset-developer-posture.test.ts",
  "tests/admin/validationResetAction.test.ts",
  "tests/admin/warningFixAffordance.test.tsx",
  "tests/admin/withAdminDevFlagDevPanelPresent.test.ts",
  "tests/admin/withAdminDevFlagLockLocation.test.ts",
  "tests/agenda/agendaAdminPreview.test.ts",
  "tests/agenda/agendaLabel.test.ts",
  "tests/agenda/agendaPurityBoundary.test.ts",
  "tests/agenda/constants.test.ts",
  "tests/agenda/extractAgendaSchedule.test.ts",
  "tests/agenda/extractAgendaScheduleServerless.test.ts",
  "tests/agenda/normalizeAgendaExtraction.test.ts",
  "tests/agenda/types.test.ts",
  "tests/api/_apiGoogleSessionRejectsWithoutCookie.test.ts",
  "tests/api/admin-snapshot-rollback-repair.test.ts",
  "tests/api/admin-staged-apply-route.test.ts",
  "tests/api/admin-staged-discard-route.test.ts",
  "tests/api/admin-sync-route.test.ts",
  "tests/api/admin/adminAlertResolve-telemetry.test.ts",
  "tests/api/admin/apply-status.test.ts",
  "tests/api/admin/dataQualityInfra-telemetry.test.ts",
  "tests/api/admin/onboardingMutations-telemetry.test.ts",
  "tests/api/admin/pendingIngestionAction-telemetry.test.ts",
  "tests/api/admin/pendingIngestionRetry-telemetry.test.ts",
  "tests/api/agenda-asset-route.test.ts",
  "tests/api/asset/_revUrlShapeContract.test.ts",
  "tests/api/cron-sync.test.ts",
  "tests/api/dataQualityIgnore.test.ts",
  "tests/api/dataQualityUnignore.test.ts",
  "tests/api/diagram-asset-route.test.ts",
  "tests/api/health.test.ts",
  "tests/api/onboarding/finalize-perrow-telemetry.test.ts",
  "tests/api/onboarding/finalizeRoleMappingsGate.test.ts",
  "tests/api/pullSheetOverrideRoute.test.ts",
  "tests/api/realtime/subscriber-token.test.ts",
  "tests/api/reel-asset-route.test.ts",
  "tests/api/rescanSheetRoute.test.ts",
  "tests/api/show-unpublish-route.test.ts",
  "tests/api/show-version.test.ts",
  "tests/api/show/unpublish-telemetry.test.ts",
  "tests/api/staged-diagram-route.defaultDeps.test.ts",
  "tests/api/staged-diagram-route.test.ts",
  "tests/api/wizard-manifest-ignore-route.test.ts",
  "tests/api/wizard-staged-apply-superseded-actor.test.ts",
  "tests/async/deferPostResponse.test.ts",
  "tests/async/mapWithConcurrency.test.ts",
  "tests/auth/_metaInfraContract.test.ts",
  "tests/auth/_metaPickerCookieContract.test.ts",
  "tests/auth/advisoryLockRpcDeadlock.test.ts",
  "tests/auth/authBoundaryStamps-telemetry.test.ts",
  "tests/auth/callback-claim-stamp.test.ts",
  "tests/auth/callback-oauth-telemetry.test.ts",
  "tests/auth/developerGatingContract.test.ts",
  "tests/auth/isAdminSession-telemetry.test.ts",
  "tests/auth/isAdminSession.test.ts",
  "tests/auth/isCurrentUserDeveloper.test.ts",
  "tests/auth/layerAwareInfraFail.test.ts",
  "tests/auth/oauth-flow.test.ts",
  "tests/auth/picker-bootstrap.test.ts",
  "tests/auth/picker/cleanupStaleEntry.test.ts",
  "tests/auth/picker/clearIdentity.test.ts",
  "tests/auth/picker/cookieEnvelope.test.ts",
  "tests/auth/picker/intentToken.test.ts",
  "tests/auth/picker/resetCrewMemberSelection.test.ts",
  "tests/auth/picker/resetPickerEpoch.test.ts",
  "tests/auth/picker/resolvePickerSelection.test.ts",
  "tests/auth/picker/rotateShareToken.test.ts",
  "tests/auth/picker/sanitizePickerRoster.test.ts",
  "tests/auth/picker/selectIdentity.test.ts",
  "tests/auth/picker/showPageChainRequest.test.ts",
  "tests/auth/picker/validatePickerAssetSession.test.ts",
  "tests/auth/requireAdmin-infra-boundary.test.ts",
  "tests/auth/requireAdmin.getClaims.test.ts",
  "tests/auth/requireAdmin.test.ts",
  "tests/auth/requireDeveloper.test.ts",
  "tests/auth/set-session-agent-fixture.test.ts",
  "tests/auth/set-session-developer-fixture.test.ts",
  "tests/auth/signInPageRedirect.test.ts",
  "tests/auth/supabaseAuthError.test.ts",
  "tests/auth/validate-next-param-show-section.test.ts",
  "tests/auth/validateErrorCode.test.ts",
  "tests/auth/validateGoogleIdentity-telemetry.test.ts",
  "tests/auth/validateGoogleIdentity.test.ts",
  "tests/auth/validateGoogleSession-telemetry.test.ts",
  "tests/auth/validateGoogleSession.test.ts",
  "tests/auth/validateNextParam.test.ts",
  "tests/codexGuard/fixture.test.ts",
  "tests/codexGuard/happyPath.test.ts",
  "tests/codexGuard/ladder.test.ts",
  "tests/codexGuard/lock.test.ts",
  "tests/codexGuard/signals.test.ts",
  "tests/codexGuard/timeouts.test.ts",
  "tests/codexGuard/usage.test.ts",
  "tests/cross-cutting/_canonicalEmailCheckContract.test.ts",
  "tests/cross-cutting/ci-workflow-speedup.test.ts",
  "tests/cross-cutting/codes.test.ts",
  "tests/cross-cutting/corpus-temp-prefix.test.ts",
  "tests/cross-cutting/cron-run-summary-scanner-safety.test.ts",
  "tests/cross-cutting/eslint-generated-dir-ignores.test.ts",
  "tests/cross-cutting/extract-spec-codes.test.ts",
  "tests/cross-cutting/identity-invalidated-two-reasons-doc-guard.test.ts",
  "tests/cross-cutting/m12-plan-pg-cron-pivot-amendment.test.ts",
  "tests/cross-cutting/no-console-exemptions.test.ts",
  "tests/cross-cutting/no-inline-email-normalization-in-plan-doc-guard.test.ts",
  "tests/cross-cutting/no-jwt-surface.test.ts",
  "tests/cross-cutting/no-load-show-crew-with-auth.test.ts",
  "tests/cross-cutting/no-m9-5-surfaces-in-m12-docs.test.ts",
  "tests/cross-cutting/no-m9-5-surfaces.test.ts",
  "tests/cross-cutting/no-npx-tsx-spawn.test.ts",
  "tests/cross-cutting/no-raw-codes.test.ts",
  "tests/cross-cutting/no-stringified-jsonb-params.test.ts",
  "tests/cross-cutting/no-vercel-cron.test.ts",
  "tests/cross-cutting/no-vestigial-middleware.test.ts",
  "tests/cross-cutting/noRawDriveHostsInCrewSurface.test.ts",
  "tests/cross-cutting/package-scripts-target-existing-files.test.ts",
  "tests/cross-cutting/pg-cron-pivot-doc-guard.test.ts",
  "tests/cross-cutting/picker-resolver-callsite-contract.test.ts",
  "tests/cross-cutting/picker-resolver-outcome-prose-guard.test.ts",
  "tests/cross-cutting/playwright-version-pin.test.ts",
  "tests/cross-cutting/pretest-gen-manifest.test.ts",
  "tests/cross-cutting/published-modal-e2e-realtime-wiring.test.ts",
  "tests/cross-cutting/rate-limit-admin-helper-var-doc-guard.test.ts",
  "tests/cross-cutting/reseed-clears-oauth-claim-doc-guard.test.ts",
  "tests/cross-cutting/resolve-show-page-access-exhaustiveness.test.ts",
  "tests/cross-cutting/serialAudit.test.ts",
  "tests/cross-cutting/supabase-boot-services.test.ts",
  "tests/cross-cutting/test-fast-deferred.test.ts",
  "tests/cross-cutting/traceability.test.ts",
  "tests/cross-cutting/unit-suite-shard-topology.test.ts",
  "tests/cross-cutting/validation-fixtures-runtime-state.test.ts",
  "tests/cross-cutting/validation-seed-rate-limit-defenses.test.ts",
  "tests/cross-cutting/validation-tooling-tz-pin.test.ts",
  "tests/cross-cutting/vitest-projects-partition.test.ts",
  "tests/cross-cutting/vitest-shard-balance.test.ts",
  "tests/data/adminEmails-telemetry.test.ts",
  "tests/data/adminEmails.test.ts",
  "tests/data/decodeRunOfShow.test.ts",
  "tests/data/diagrams.test.ts",
  "tests/data/downgradeRunOfShow.test.ts",
  "tests/data/financialsEntitlement.test.ts",
  "tests/data/getShowForViewer-rooms-projection.test.ts",
  "tests/data/getShowForViewer.cache.test.ts",
  "tests/data/getShowForViewer.parallel.test.ts",
  "tests/data/getShowForViewer.readOrder.test.ts",
  "tests/data/getShowForViewerFlight.test.ts",
  "tests/data/getShowForViewerRunOfShow.test.ts",
  "tests/data/getShowForViewerSourceAnchors.test.ts",
  "tests/data/hotelVisibility.test.ts",
  "tests/data/listShowsForCrew.test.ts",
  "tests/data/loadShowShareToken.test.ts",
  "tests/data/nameMatch.test.ts",
  "tests/data/normalizeDateRestriction.test.ts",
  "tests/data/openingReel.test.ts",
  "tests/data/setAdminDeveloper.test.ts",
  "tests/data/show-page-role-spoof.test.ts",
  "tests/data/transportOwnerResolve.test.ts",
  "tests/data/verifyResyncExpectedMap.test.ts",
  "tests/data/viewerContext.test.ts",
  "tests/db/advisory-lock-env.test.ts",
  "tests/db/backfill-validation-source-anchors.test.ts",
  "tests/db/coerceJsonbObject.test.ts",
  "tests/db/cutover-drop-m9-5.test.ts",
  "tests/db/pendingSyncsSourceAnchorsColumn.test.ts",
  "tests/db/runOfShowColumn.test.ts",
  "tests/db/schema-manifest-lib.test.ts",
  "tests/db/schema.test.ts",
  "tests/db/seed-restage-fixture.test.ts",
  "tests/db/selectionsResetAtColumn.test.ts",
  "tests/db/show-change-log-change-kind-taxonomy.test.ts",
  "tests/db/showCacheRevalidateCoverage.test.ts",
  "tests/db/undo-change-lock-order.test.ts",
  "tests/db/undo-change-no-phantom-columns.test.ts",
  "tests/log/_auditableMutations.shape.test.ts",
  "tests/log/_metaAdminOutcomeContract.test.ts",
  "tests/log/_metaAppEventsWriter.test.ts",
  "tests/log/_metaMutationSurfaceObservability.test.ts",
  "tests/log/authReturnedErrorTaps.test.ts",
  "tests/log/callbackUsesSerializeError.test.ts",
  "tests/log/correlationSeeding.test.ts",
  "tests/log/emitLeadRoleApplied.test.ts",
  "tests/log/emitRoleTokenMapped.test.ts",
  "tests/log/logAdminOutcome.test.ts",
  "tests/log/logAdminOutcomeIntegration.test.ts",
  "tests/log/logger.test.ts",
  "tests/log/mutationSurface/enumerate.test.ts",
  "tests/log/mutationSurface/exemptions.test.ts",
  "tests/log/nonAuthTaps.test.ts",
  "tests/log/nullcodeBatch2Emission.test.ts",
  "tests/log/persist.test.ts",
  "tests/log/persistHealth.test.ts",
  "tests/log/persistStrict.test.ts",
  "tests/log/requestContext.test.ts",
  "tests/log/sanitize.test.ts",
  "tests/log/serializeError.test.ts",
  "tests/notify/autoPublishUndoBatchTemplate.test.ts",
  "tests/notify/autoPublishUndoTemplate.test.ts",
  "tests/notify/candidates.test.ts",
  "tests/notify/config.test.ts",
  "tests/notify/constants-producers.test.ts",
  "tests/notify/constants-values.test.ts",
  "tests/notify/deliver-auto-publish-undo.test.ts",
  "tests/notify/deliver.test.ts",
  "tests/notify/deliverBatch.test.ts",
  "tests/notify/digest.test.ts",
  "tests/notify/digestSyncProblemCompat.test.ts",
  "tests/notify/email-delivery-failed-reconcile.test.ts",
  "tests/notify/escapeHtml.test.ts",
  "tests/notify/idempotencyKey.test.ts",
  "tests/notify/monitorDigest.autoApplied.test.ts",
  "tests/notify/monitorDigest.autofix.test.ts",
  "tests/notify/monitorDigest.autofixAnchors.test.ts",
  "tests/notify/monitorDigest.drift.test.ts",
  "tests/notify/monitorDigest.filterParity.test.ts",
  "tests/notify/monitorDigest.infra.test.ts",
  "tests/notify/monitorDigest.window.test.ts",
  "tests/notify/monitorNewShowGaps.test.ts",
  "tests/notify/monitorWatermark.infra.test.ts",
  "tests/notify/notify-route.test.ts",
  "tests/notify/realtimeProblemBatchTemplate.test.ts",
  "tests/notify/recipients.test.ts",
  "tests/notify/recovery-resolution.test.ts",
  "tests/notify/renderDigest.monitor.test.ts",
  "tests/notify/renderDigest.newShowGaps.test.ts",
  "tests/notify/resend-dep.test.ts",
  "tests/notify/run-notify.test.ts",
  "tests/notify/runDigestNotify.monitor.test.ts",
  "tests/notify/runMaintenance.botLogin.test.ts",
  "tests/notify/send.test.ts",
  "tests/notify/singleFlightLock.test.ts",
  "tests/notify/siteOrigin.test.ts",
  "tests/notify/stall-detector.test.ts",
  "tests/notify/sync-problem-codes.test.ts",
  "tests/notify/templates.test.ts",
  "tests/notify/toggle-getters.test.ts",
  "tests/observe/_metaAlertsRedactionContract.test.ts",
  "tests/observe/_metaReadOnlyQueryCore.test.ts",
  "tests/observe/adminErrorWiring.test.tsx",
  "tests/observe/args.test.ts",
  "tests/observe/captureBoundaryError.test.ts",
  "tests/observe/clientErrorRoute.test.ts",
  "tests/observe/clientErrorTransport.test.ts",
  "tests/observe/clientLog.test.ts",
  "tests/observe/codes.test.ts",
  "tests/observe/collect.test.ts",
  "tests/observe/crewError.test.tsx",
  "tests/observe/dispatch.test.ts",
  "tests/observe/env.test.ts",
  "tests/observe/errorBoundaryLayout.test.tsx",
  "tests/observe/format.test.ts",
  "tests/observe/getCronHealth.test.ts",
  "tests/observe/globalError.test.tsx",
  "tests/observe/globalErrorListener.test.tsx",
  "tests/observe/nextConfigSentry.test.ts",
  "tests/observe/parseSampleRate.test.ts",
  "tests/observe/queryAlerts.test.ts",
  "tests/observe/queryChangeLog.test.ts",
  "tests/observe/queryDeferred.test.ts",
  "tests/observe/queryEvents.test.ts",
  "tests/observe/queryFailures.test.ts",
  "tests/observe/queryStaged.test.ts",
  "tests/observe/querySyncLog.test.ts",
  "tests/observe/queryWarnings.test.ts",
  "tests/observe/queryWatch.test.ts",
  "tests/observe/reportClientError.test.ts",
  "tests/observe/scrubSentryEvent.test.ts",
  "tests/observe/sentryNoopGate.test.ts",
  "tests/observe/serializeWarning.test.ts",
  "tests/observe/serverMigrationSpot.test.ts",
  "tests/observe/showRealtimeBridge.test.tsx",
  "tests/observe/tileErrorBoundary.test.tsx",
  "tests/onboarding/_metaRescanDecisionInvariants.test.ts",
  "tests/onboarding/applyRescanDecisionUnderLock.test.ts",
  "tests/onboarding/blockerDisplayName.test.ts",
  "tests/onboarding/cleanupAbandonedFinalize.test.ts",
  "tests/onboarding/cleanupStuckEligibility.test.ts",
  "tests/onboarding/enrichAgendaIntegration.test.ts",
  "tests/onboarding/finalize-cas.test.ts",
  "tests/onboarding/finalize.test.ts",
  "tests/onboarding/finalizeApprovalRace.test.ts",
  "tests/onboarding/finalizeCasStream.test.ts",
  "tests/onboarding/finalizeInlineRescan.test.ts",
  "tests/onboarding/finalizeNoDriveExport.test.ts",
  "tests/onboarding/finalizeOverrideConsistencyGate.test.ts",
  "tests/onboarding/finalizeProgress.test.ts",
  "tests/onboarding/finalizeRevalidate.test.ts",
  "tests/onboarding/finalizeStream.test.ts",
  "tests/onboarding/firstSeenLiveStaged.test.ts",
  "tests/onboarding/firstSeenStagedWarnings.test.ts",
  "tests/onboarding/pendingIngestionsWizardActions.test.ts",
  "tests/onboarding/prepareOnboardingFilesXlsxBytes.test.ts",
  "tests/onboarding/prepareRoleMappingOverlay.test.ts",
  "tests/onboarding/prepareSourceAnchorsRegion.test.ts",
  "tests/onboarding/prepareSourceCellAnchors.test.ts",
  "tests/onboarding/pullSheetOverridePropagation.test.ts",
  "tests/onboarding/reapStaleSessions.test.ts",
  "tests/onboarding/reapStaleSessionsRoute.test.ts",
  "tests/onboarding/rescanCheckpointReopen.test.ts",
  "tests/onboarding/rescanDecision.test.ts",
  "tests/onboarding/rescanOverrideLockedSnapshot.test.ts",
  "tests/onboarding/rescanRoleMappingOverlay.test.ts",
  "tests/onboarding/retryLiveRowConflictFreshTx.test.ts",
  "tests/onboarding/retrySingleFile.test.ts",
  "tests/onboarding/scanProgress.test.ts",
  "tests/onboarding/scanResponse.test.ts",
  "tests/onboarding/scanRoute.test.ts",
  "tests/onboarding/scanRouteAlertEmit.test.ts",
  "tests/onboarding/serverActions.test.ts",
  "tests/onboarding/sessionLifecycle.test.ts",
  "tests/onboarding/shadowPayload.test.ts",
  "tests/onboarding/wizardScopedReapply.test.ts",
  "tests/reports/_amendmentContractMetaTest.test.ts",
  "tests/reports/_metaInfraContract.test.ts",
  "tests/reports/auth.test.ts",
  "tests/reports/botLoginAlert.test.ts",
  "tests/reports/issueBody.test.ts",
  "tests/reports/leaseProtocol.test.ts",
  "tests/reports/recoveredLeaseHolder.test.ts",
  "tests/reports/stateGatedAlert.test.ts",
  "tests/reports/submit.botLoginResolve.test.ts",
  "tests/reports/tailUpdateMiss.test.ts",
  "tests/scripts/extract-spec-codes-cli.test.ts",
  "tests/scripts/validation-check-seed-freshness-skew.test.ts",
  "tests/scripts/validation-env.test.ts",
  "tests/scripts/validation-fixtures.test.ts",
  "tests/scripts/validation-reseed.test.ts",
  "tests/scripts/validation-smoke-base-url.test.ts",
  "tests/scripts/validation-target.test.ts",
  "tests/show/confirmUnpublishFormBusy.test.tsx",
  "tests/show/crewLinkNotFound.test.tsx",
  "tests/show/crewShellUnmatchedViewer.test.tsx",
  "tests/show/flow8Repick.test.tsx",
  "tests/show/loadRosterSanitizeBoundary.test.tsx",
  "tests/show/page-today-uses-now-utility.test.ts",
  "tests/show/pageSelectionResetBanner.test.ts",
  "tests/show/pickerAffordance.test.tsx",
  "tests/show/resolvedArmCrewMembersGuard.test.tsx",
  "tests/show/showUnavailablePaused.test.tsx",
  "tests/show/unpublishConfirmAction.test.ts",
  "tests/show/unpublishConfirmPage.test.tsx",
  "tests/show/unpublishConfirmState.test.ts",
  "tests/show/unpublishRoutePrecedence.test.ts",
  "tests/specLint/_metaPureCore.test.ts",
  "tests/specLint/citations.test.ts",
  "tests/specLint/cli.test.ts",
  "tests/specLint/copyRules.test.ts",
  "tests/specLint/numerics.test.ts",
  "tests/specLint/parse.test.ts",
  "tests/specLint/run.test.ts",
  "tests/specLint/sections.test.ts",
  "tests/supabase/env.test.ts",
  "tests/sync/_advisoryLockSingleHolderContract.test.ts",
  "tests/sync/_inTxAdminAlertContract.test.ts",
  "tests/sync/_insertParamsArityContract.test.ts",
  "tests/sync/_livePartitionClassificationContract.test.ts",
  "tests/sync/_metaInfraContract.test.ts",
  "tests/sync/_metaLeadRoleAppliedTopology.test.ts",
  "tests/sync/_mi11GateNoUngatedApplyContract.test.ts",
  "tests/sync/_partitionScopeContract.test.ts",
  "tests/sync/_pendingSnapshotUploadsContract.test.ts",
  "tests/sync/_phase1WarningBridgeContract.test.ts",
  "tests/sync/_phase2ArgsParityContract.test.ts",
  "tests/sync/_phase2InvariantContract.test.ts",
  "tests/sync/_scopeCheckContract.test.ts",
  "tests/sync/_secondCopyApplyTripwire.test.ts",
  "tests/sync/_sharedDriveSupportContract.test.ts",
  "tests/sync/_storageWriteSurfaceContract.test.ts",
  "tests/sync/_streamingHashContract.test.ts",
  "tests/sync/acknowledgeChanges.test.ts",
  "tests/sync/applyParseResult.identityLink.test.ts",
  "tests/sync/applyParseResultScheduleDay.test.ts",
  "tests/sync/applyParseResultUseRaw.test.ts",
  "tests/sync/applyRawParseNoOverride.test.ts",
  "tests/sync/applyStaged.authFloors.test.ts",
  "tests/sync/applyStaged.lockContention-telemetry.test.ts",
  "tests/sync/applyStaged.test.ts",
  "tests/sync/applyStaged.wizardDriveReverify.test.ts",
  "tests/sync/applyStagedCore.livePartition.test.ts",
  "tests/sync/applyStagedCore.test.ts",
  "tests/sync/applyStagedReadCoercion.test.ts",
  "tests/sync/applyStagedRestageBytes.test.ts",
  "tests/sync/assetRecovery.test.ts",
  "tests/sync/assetRecoveryXlsxMedia.test.ts",
  "tests/sync/assetStreamTimeout.test.ts",
  "tests/sync/attachWarningAnchors.test.ts",
  "tests/sync/blockDisappearance.test.ts",
  "tests/sync/boundedBytes.test.ts",
  "tests/sync/changeLog/fieldChanges.test.ts",
  "tests/sync/cronDriveClientTimeout.test.ts",
  "tests/sync/cronSyncEscapedFailureAlert.test.ts",
  "tests/sync/cronSyncThrowAttribution.test.ts",
  "tests/sync/def2-archived-guard.test.ts",
  "tests/sync/def3-manual-resync.test.ts",
  "tests/sync/def4-archived-skip.test.ts",
  "tests/sync/defaultDriveClientSheetsFieldsMask.test.ts",
  "tests/sync/diagramGc.test.ts",
  "tests/sync/discardStaged.test.ts",
  "tests/sync/discardStagedRevalidate.test.ts",
  "tests/sync/drive-fetch-failed-producer.test.ts",
  "tests/sync/driveClientImplCompleteness.test.ts",
  "tests/sync/driveMetadataTimeout.test.ts",
  "tests/sync/embeddedImages.test.ts",
  "tests/sync/embeddedImagesXlsx.test.ts",
  "tests/sync/enrichAgenda-telemetry.test.ts",
  "tests/sync/enrichAgenda.correlation-telemetry.test.ts",
  "tests/sync/enrichAgenda.test.ts",
  "tests/sync/enrichSignalForwarding.test.ts",
  "tests/sync/enrichTransportAssignees.test.ts",
  "tests/sync/enrichVenueGeocode.test.ts",
  "tests/sync/enrichWithDrivePins.runOfShow.test.ts",
  "tests/sync/enrichWithDrivePins.test.ts",
  "tests/sync/errorPayloadCause.test.ts",
  "tests/sync/feed/isCrewDomainChangeKind.test.ts",
  "tests/sync/feed/readShowChangeFeed.infra.test.ts",
  "tests/sync/feed/readShowChangeFeed.parallel.test.ts",
  "tests/sync/firstPublishedAlertContextNoToken.meta.test.ts",
  "tests/sync/firstSeenPendingIngestion.test.ts",
  "tests/sync/flowCLivePendingApplyGate.test.ts",
  "tests/sync/heartbeat-write.test.ts",
  "tests/sync/holds/undoChange.infra.test.ts",
  "tests/sync/identityLinkRenames.test.ts",
  "tests/sync/jsonbBoundaryRepresentation.meta.test.ts",
  "tests/sync/lastCheckedAt.db.test.ts",
  "tests/sync/lockedShowTx.test.ts",
  "tests/sync/manual-sync-producer-parity.test.ts",
  "tests/sync/mi11GateActions.test.ts",
  "tests/sync/mi11GateActionsInfra.test.ts",
  "tests/sync/mockDriveClient.test.ts",
  "tests/sync/no-direct-drive-folder-env.test.ts",
  "tests/sync/no-unpinned-drive-export-callers.test.ts",
  "tests/sync/onboarding.test.ts",
  "tests/sync/parse-error-last-good-producer.test.ts",
  "tests/sync/parseSheetCallSiteGuard.test.ts",
  "tests/sync/perFileProcessor.test.ts",
  "tests/sync/phase1.decision-rule.test.ts",
  "tests/sync/phase1.test.ts",
  "tests/sync/phase1WarningBridge.test.ts",
  "tests/sync/phase2.test.ts",
  "tests/sync/phase2RoleMappings.test.ts",
  "tests/sync/priorRunOfShowDecode.test.ts",
  "tests/sync/promoteSnapshot.test.ts",
  "tests/sync/promoteSnapshotClaimSymmetry.test.ts",
  "tests/sync/promoteSnapshotDefaultStorage.test.ts",
  "tests/sync/promoteSnapshotRevalidate.test.ts",
  "tests/sync/pullSheetOverrideCoerce.test.ts",
  "tests/sync/pullSheetOverridePrepare.test.ts",
  "tests/sync/pullSheetOverrideReconcile.test.ts",
  "tests/sync/readShowPriorWarningsRaw.test.ts",
  "tests/sync/recovery-resolution-syncpath.test.ts",
  "tests/sync/reelColumnsContract.test.ts",
  "tests/sync/resync-shrink-held-producer.test.ts",
  "tests/sync/revisionTimesMatch.test.ts",
  "tests/sync/roleMappingOverlay.test.ts",
  "tests/sync/roleMappingThreading.test.ts",
  "tests/sync/roleVocabDriftDatabaseUrlResolver.test.ts",
  "tests/sync/roleVocabDriftResync.test.ts",
  "tests/sync/runManualStageForFirstSeen.test.ts",
  "tests/sync/runManualSyncForShow.test.ts",
  "tests/sync/runOfShowConfirmedReplace.test.ts",
  "tests/sync/runOfShowLiveWiring.meta.test.ts",
  "tests/sync/runOfShowSyncLogChannel.test.ts",
  "tests/sync/runPushSyncForShow.test.ts",
  "tests/sync/runScheduledCronSync.adapter.test.ts",
  "tests/sync/snapshotAssets.test.ts",
  "tests/sync/snapshotAssetsXlsxMedia.test.ts",
  "tests/sync/syncDiagramRevalidate.test.ts",
  "tests/sync/syncLog.test.ts",
  "tests/sync/syncLogSink.persistence.test.ts",
  "tests/sync/syncRevalidate.test.ts",
  "tests/sync/syntheticDriveFileId.test.ts",
  "tests/sync/timestampInstantSafety.meta.test.ts",
  "tests/sync/unexpectedParentLog.test.ts",
  "tests/sync/unpublishBinding.test.ts",
  "tests/sync/unpublishShow.test.ts",
  "tests/sync/useRawDecisionState.test.ts",
  "tests/sync/useRawOverlay.test.ts",
  "tests/sync/verifyReelOnApply.test.ts",
  "tests/sync/withStepTimeout.test.ts",
] as const;

export const PARALLEL_TEST_GLOBS = [
  "tests/components/**/*.test.{ts,tsx}",
  "tests/help/**/*.test.{ts,tsx}",
  "tests/messages/**/*.test.{ts,tsx}",
  "tests/app/**/*.test.{ts,tsx}",
  "tests/crew/**/*.test.{ts,tsx}",
  "tests/visibility/**/*.test.{ts,tsx}",
  "tests/realtime/**/*.test.{ts,tsx}",
  "tests/time/**/*.test.{ts,tsx}",
  "tests/styles/**/*.test.{ts,tsx}",
  "tests/format/**/*.test.{ts,tsx}",
  "tests/staging/**/*.test.{ts,tsx}",
  "tests/sheet-links/**/*.test.{ts,tsx}",
  "tests/lib/**/*.test.{ts,tsx}",
  "tests/email/**/*.test.{ts,tsx}",
  "tests/config/**/*.test.{ts,tsx}",
  "tests/me/**/*.test.{ts,tsx}",
  "tests/migration/**/*.test.{ts,tsx}",
  "tests/validation/**/*.test.{ts,tsx}",
  "tests/adminAlerts/**/*.test.{ts,tsx}",
  "tests/fixtures/**/*.test.{ts,tsx}",
  // Phase 2 (spec 2026-07-19-ci-unit-suite-phase2-serial-audit §2): verified
  // via the same closed-port + fileParallelism protocol on 2026-07-19
  // (178 passed / 2,745 tests green). tests/parser are fixture-corpus READERS —
  // safe in the parallel phase because the corpus WRITER
  // (tests/sync/dev-routing.test.ts) stays serial and the two phases never
  // overlap. The nightly mutationHarness.* files match tests/parser/** but are
  // excluded from BOTH default projects (see vitest.config.ts).
  "tests/parser/**/*.test.{ts,tsx}",
  "tests/drive/**/*.test.{ts,tsx}",
  "tests/cron/**/*.test.{ts,tsx}",
  "tests/dataQuality/**/*.test.{ts,tsx}",
  "tests/appSettings/**/*.test.{ts,tsx}",
  "tests/geocoding/**/*.test.{ts,tsx}",
  "tests/design/**/*.test.{ts,tsx}",
  "tests/dates/**/*.test.{ts,tsx}",
  "tests/showLifecycle/**/*.test.{ts,tsx}",
  "tests/invariants/**/*.test.{ts,tsx}",
  "tests/github/**/*.test.{ts,tsx}",
  "tests/venue/**/*.test.{ts,tsx}",
  "tests/sample.test.ts",
];

// Parallel-set files that assert ON-DISK state a SERIAL test mutates mid-run
// (today: lib/admin/__generated__/devPanelPresent.ts, rewritten by
// tests/admin/withAdminDevFlagDevPanelPresent.test.ts and asserted `false` by
// DevToolsRow.absent). test:fast excludes these from the overlapped parallel
// phase (VITEST_TEST_FAST=1) and re-runs them in a post-serial epilogue when the
// file is guaranteed restored. Repo-relative PATHS, not globs — triple use:
// vitest exclude pattern, epilogue CLI filter, meta-test existsSync
// (tests/cross-cutting/test-fast-deferred.test.ts pins all of it; spec §4.1.3).
export const TEST_FAST_DEFERRED = ["tests/components/admin/settings/DevToolsRow.absent.test.tsx"];
