// GENERATED by scripts/with-admin-dev-flag.mjs at build time; committed value is the
// fail-closed default. The build tool overwrites this to match ADMIN_DEV_PANEL_ENABLED
// before `next build` and restores `false` on exit (clean working tree).
export const DEV_PANEL_PRESENT = false;
