// Generated by scripts/extract-internal-code-enums.ts. Do not edit by hand.

export type InternalCodeEnumPayload = {
  source: string;
};

export const INTERNAL_CODE_ENUMS = {
  ADMIN_SESSION_LOOKUP_FAILED: {
    source: "admin_alerts.code"
  },
  AGENDA_BLOCK_UNRESOLVED: {
    source: "parse_warnings.code"
  },
  AGENDA_DAY_AMBIGUOUS: {
    source: "parse_warnings.code"
  },
  AGENDA_DAY_EMPTIED: {
    source: "parse_warnings.code"
  },
  AGENDA_DAY_TRUNCATED: {
    source: "parse_warnings.code"
  },
  AGENDA_GRID_MALFORMED: {
    source: "parse_warnings.code"
  },
  AMBIGUOUS_EMAIL_BINDING: {
    source: "admin_alerts.code"
  },
  ASSET_RECOVERY_BYTES_EXCEEDED: {
    source: "admin_alerts.code"
  },
  ASSET_RECOVERY_DRIFT_COOLDOWN: {
    source: "admin_alerts.code"
  },
  ASSET_RECOVERY_REVISION_DRIFT: {
    source: "admin_alerts.code"
  },
  COLUMN_HEADER_AUTOCORRECTED: {
    source: "parse_warnings.code"
  },
  CONCURRENT_SYNC_SKIPPED: {
    source: "pending_ingestions.last_error_code"
  },
  DAY_RESTRICTION_DOUBLE_LOCATION: {
    source: "parse_warnings.code"
  },
  drive_error: {
    source: "shows.last_sync_status"
  },
  DRIVE_FETCH_FAILED: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  DRIVE_METADATA_MISSING: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  DUPLICATE_REVIEWER_CHOICE: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  EMAIL_DELIVERY_FAILED: {
    source: "admin_alerts.code"
  },
  EMAIL_NOT_CONFIGURED: {
    source: "admin_alerts.code"
  },
  EMBEDDED_RECOVERY_REQUIRES_RESTAGE: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  EXTRA_REVIEWER_CHOICE: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  FIELD_UNREADABLE: {
    source: "parse_warnings.code"
  },
  FINALIZE_OWNED_SHOW: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  FOLDER_NOT_FOUND: {
    source: "pending_ingestions.last_error_code"
  },
  FOLDER_NOT_SHARED: {
    source: "pending_ingestions.last_error_code"
  },
  GOOGLE_NO_CREW_MATCH: {
    source: "admin_alerts.code"
  },
  IDEMPOTENCY_IN_FLIGHT: {
    source: "admin_alerts.code"
  },
  INVALID_REVIEWER_ACTION: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  LIVE_ROW_CONFLICT: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  "MI-1_VERSION_DETECTION_FAILED": {
    source: "parse_warnings.code,pending_ingestions.last_error_code"
  },
  "MI-2_EMPTY_TITLE": {
    source: "pending_ingestions.last_error_code"
  },
  "MI-3_NO_VALID_DATES": {
    source: "pending_ingestions.last_error_code"
  },
  "MI-4_NO_CREW": {
    source: "pending_ingestions.last_error_code"
  },
  "MI-5_NO_ROOMS": {
    source: "pending_ingestions.last_error_code"
  },
  "MI-5a_DUPLICATE_CREW_NAME": {
    source: "pending_ingestions.last_error_code"
  },
  "MI-5b_DUPLICATE_CREW_EMAIL": {
    source: "pending_ingestions.last_error_code"
  },
  MISSING_REVIEWER_CHOICE: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  ok: {
    source: "shows.last_sync_status"
  },
  ONBOARDING_FINALIZE_INTERNAL_ERROR: {
    source: "pending_ingestions.last_error_code"
  },
  ONBOARDING_LEGACY_ROW_AMBIGUOUS: {
    source: "pending_ingestions.last_error_code"
  },
  OPERATOR_ERROR_INCOMPLETE_FOLDER_METADATA: {
    source: "pending_ingestions.last_error_code"
  },
  OPERATOR_ERROR_NOT_FOLDER: {
    source: "pending_ingestions.last_error_code"
  },
  parse_error: {
    source: "shows.last_sync_status"
  },
  PARSE_ERROR_LAST_GOOD: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  PENDING_INGESTION_NOT_FOUND: {
    source: "pending_ingestions.last_error_code"
  },
  pending_review: {
    source: "shows.last_sync_status"
  },
  PENDING_SYNC_NOT_FOUND: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  PICKER_BOOTSTRAP_RESOLVE_SHOW_FAILED: {
    source: "admin_alerts.code"
  },
  PICKER_BOOTSTRAP_RPC_FAILED: {
    source: "admin_alerts.code"
  },
  PICKER_EPOCH_RESET: {
    source: "admin_alerts.code"
  },
  PICKER_INVALID_INPUT: {
    source: "admin_alerts.code"
  },
  PICKER_RESOLVER_LOOKUP_FAILED: {
    source: "admin_alerts.code"
  },
  PICKER_SELECTION_RACE: {
    source: "admin_alerts.code"
  },
  PULL_SHEET_AMBIGUOUS_FORMAT: {
    source: "parse_warnings.code"
  },
  PULL_SHEET_PARSE_PARTIAL: {
    source: "parse_warnings.code"
  },
  PULL_SHEET_UNKNOWN_VARIANT: {
    source: "parse_warnings.code"
  },
  REPORT_HORIZON_EXPIRED: {
    source: "admin_alerts.code"
  },
  REPORT_LOOKUP_INCONCLUSIVE: {
    source: "admin_alerts.code"
  },
  REPORT_PIPELINE_FAILED: {
    source: "admin_alerts.code"
  },
  ROLE_TOKEN_AUTOCORRECTED: {
    source: "parse_warnings.code"
  },
  SCHEDULE_TIME_UNPARSED: {
    source: "parse_warnings.code"
  },
  SECTION_HEADER_AUTOCORRECTED: {
    source: "parse_warnings.code"
  },
  SECTION_HEADER_NO_FIELDS: {
    source: "parse_warnings.code"
  },
  sheet_unavailable: {
    source: "shows.last_sync_status"
  },
  SHEET_UNAVAILABLE: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  SHOW_FIRST_PUBLISHED: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  SHOW_UNPUBLISHED: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  STAGE_WORD_AUTOCORRECTED: {
    source: "parse_warnings.code"
  },
  STAGED_PARSE_OUTDATED: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  STAGED_PARSE_OUTDATED_AT_PHASE_D: {
    source: "pending_ingestions.last_error_code"
  },
  STAGED_PARSE_RESTAGED_INLINE: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  STAGED_PARSE_RESULT_CORRUPT: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  STAGED_PARSE_REVISION_RACE: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  STAGED_PARSE_REVISION_RACE_COOLDOWN: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  STAGED_PARSE_REVISION_RACE_DURING_FINALIZE: {
    source: "pending_ingestions.last_error_code"
  },
  STAGED_PARSE_SOURCE_GONE: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  STAGED_PARSE_SOURCE_OUT_OF_SCOPE: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  STAGED_PARSE_SUPERSEDED: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  STAGED_REVIEW_ITEMS_CORRUPT: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  STALE_DISCARD_REJECTED: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  SYNC_FILE_FAILED: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  SYNC_INFRA_ERROR: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  SYNC_STALLED: {
    source: "admin_alerts.code"
  },
  SYNC_STEP_TIMEOUT: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  TRAVEL_FLIGHT_AMBIGUOUS_TABLE: {
    source: "parse_warnings.code"
  },
  TRAVEL_FLIGHT_NAME_UNMATCHED: {
    source: "parse_warnings.code"
  },
  TRAVEL_FLIGHT_UNPARSEABLE: {
    source: "parse_warnings.code"
  },
  TYPO_NORMALIZED: {
    source: "parse_warnings.code"
  },
  UNKNOWN_DAY_RESTRICTION: {
    source: "parse_warnings.code"
  },
  UNKNOWN_FIELD: {
    source: "parse_warnings.code"
  },
  UNKNOWN_ROLE_TOKEN: {
    source: "parse_warnings.code"
  },
  UNKNOWN_SECTION_HEADER: {
    source: "parse_warnings.code"
  },
  UNPUBLISH_TOKEN_CONSUMED: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  UNPUBLISH_TOKEN_EXPIRED: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  WATCH_CHANNEL_ORPHANED: {
    source: "admin_alerts.code"
  },
  WEBHOOK_CHANNEL_INACTIVE: {
    source: "admin_alerts.code"
  },
  WEBHOOK_HEADERS_MISSING: {
    source: "admin_alerts.code"
  },
  WEBHOOK_TOKEN_INVALID: {
    source: "admin_alerts.code"
  },
  WIZARD_ISOLATION_INDEXES_MISSING: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  WIZARD_REVIEWER_CHOICES_VERSION_UNSUPPORTED: {
    source: "pending_ingestions.last_error_code"
  },
  WIZARD_SESSION_SUPERSEDED: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  WIZARD_SESSION_SUPERSEDED_DURING_SCAN: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  },
  WIZARD_SESSION_SUPERSEDED_RACE: {
    source: "admin_alerts.code,pending_ingestions.last_error_code"
  }
} as const satisfies Record<string, InternalCodeEnumPayload>;

export type InternalCodeEnum = keyof typeof INTERNAL_CODE_ENUMS;
