/**
 * app/show/[slug]/[shareToken]/page.tsx (M11.5 §B Task C1)
 *
 * The crew page route. Replaces the legacy slug-only `app/show/[slug]/page.tsx`.
 *
 * R35 amendment: the share-token is a required path segment, not a query
 * parameter — a slug-only URL hits Next's 404 at the file-system level
 * (no fallback render). The route owns auth resolution via
 * `resolveShowPageAccess` (lib/auth/picker/resolveShowPageAccess.ts) and
 * dispatches on the 11-arm discriminated union the helper returns.
 *
 * Surfaces consumed (Pin-2 contracts, all owned by §A / Codex):
 *   - resolveShowPageAccess — archived/admin/unpublished/Google-session/
 *     cookie chain
 *   - getShowForViewer       — render data for the admin/crew viewer
 *   - createSupabaseServiceRoleClient — roster read for picker render
 *
 * Components consumed (M11.5 §B):
 *   - TerminalFailure        — infra_error / data-load failures
 *   - SignInOrSkipGate       — no_auth first-contact + google_mismatch
 *   - PickerInterstitial     — picker render + stale-credential banners
 *   - ShowBody / IdentityChip — resolved + admin viewers
 *
 * Atomicity guard (P-R29 Fix-3):
 *   gateSkip (?gate=skip) is honored ONLY when reason === 'first_contact'.
 *   A hand-crafted `?gate=skip` on a `google_mismatch` URL re-renders
 *   the Mode-B gate; the only legal path to ?gate=skip on mismatch is
 *   the clearIdentityAndSkip Server Action that pairs cookie-clear with
 *   the redirect.
 *
 * P-R5 Fix-1: every external data load (`getShowForViewer`, `loadRoster`)
 * is wrapped in try/catch and routed to <TerminalFailure> on failure;
 * the page never throws an uncaught error into Next's generic boundary.
 */
import { notFound, redirect } from "next/navigation";

import { TerminalFailure } from "@/components/auth/TerminalFailure";
import { buildShowPageChainRequest } from "@/lib/auth/picker/showPageChainRequest";
import { resolveShowPageAccess } from "@/lib/auth/picker/resolveShowPageAccess";
import { getShowForViewer, type Viewer } from "@/lib/data/getShowForViewer";
import { createSupabaseServiceRoleClient } from "@/lib/supabase/server";

import { PickerInterstitial } from "./_PickerInterstitial";
import { SignInOrSkipGate } from "./_SignInOrSkipGate";
import { ShowBody } from "./_ShowBody";

type RosterRow = {
  id: string;
  name: string;
  role: string;
  role_flags: string[];
  claimed_via_oauth_at: string | null;
};

async function loadRoster(showId: string): Promise<RosterRow[]> {
  const supabase = createSupabaseServiceRoleClient();
  const { data, error } = await supabase
    .from("crew_members")
    .select("id, name, role, role_flags, claimed_via_oauth_at")
    .eq("show_id", showId)
    .order("name", { ascending: true });
  if (error) throw new Error("roster lookup failed");
  return (data ?? []) as RosterRow[];
}

export default async function ShowPage({
  params,
  searchParams,
}: {
  params: Promise<{ slug: string; shareToken: string }>;
  searchParams: Promise<{ gate?: string }>;
}) {
  const { slug, shareToken } = await params;
  const { gate } = await searchParams;
  const gateSkip = gate === "skip";

  const req = await buildShowPageChainRequest();
  const result = await resolveShowPageAccess({ slug, shareToken, req });

  switch (result.kind) {
    case "archived":
      // R27: archived 404s for ALL viewers including admin — admins
      // debug archived shows via /admin/show/<slug>.
      notFound();
    // falls through (notFound() throws)

    case "unpublished":
      notFound();
    // falls through

    case "show_unavailable":
      // Show was archived/unpublished after the cookie was minted, OR
      // the slug+token pair never resolved to a row. Either way the
      // crew route 404s — admins use the admin route.
      notFound();
    // falls through

    case "infra_error":
      return (
        <TerminalFailure code={result.code as never} retryHref={`/show/${slug}/${shareToken}`} />
      );

    case "needs_picker_bootstrap": {
      // Server Components cannot mint cookies; redirect to the Route
      // Handler that legally mutates `__Host-fxav_picker`. The intent
      // token (R41-R5 CSRF defense) is generated by the helper.
      const nextUrl = `/show/${slug}/${shareToken}`;
      redirect(
        `/api/auth/picker-bootstrap?next=${encodeURIComponent(
          nextUrl,
        )}&t=${encodeURIComponent(result.intentToken)}`,
      );
    }

    case "admin": {
      const viewer: Viewer = { kind: "admin" };
      let data;
      try {
        data = await getShowForViewer(result.showId, viewer);
      } catch {
        return (
          <TerminalFailure
            code="PICKER_RESOLVER_LOOKUP_FAILED"
            retryHref={`/show/${slug}/${shareToken}`}
          />
        );
      }
      return (
        <ShowBody
          slug={slug}
          showId={result.showId}
          viewer={viewer}
          data={data}
          identityChip={null}
        />
      );
    }

    case "resolved": {
      const viewer: Viewer = {
        kind: "crew",
        crewMemberId: result.crewMemberId,
      };
      let data;
      try {
        data = await getShowForViewer(result.showId, viewer);
      } catch {
        return (
          <TerminalFailure
            code="PICKER_RESOLVER_LOOKUP_FAILED"
            retryHref={`/show/${slug}/${shareToken}`}
          />
        );
      }
      // Defense-in-depth: crewMembers is typed as a required array and the
      // helper always constructs one (getShowForViewer.ts:305), but a
      // malformed/degraded projection must degrade to a chip-less render —
      // never an uncaught TypeError into Next's generic boundary (P-R5 Fix-1).
      const crew = data.crewMembers?.find((c) => c.id === result.crewMemberId);
      return (
        <ShowBody
          slug={slug}
          showId={result.showId}
          viewer={viewer}
          data={data}
          identityChip={crew ? { name: crew.name, role: crew.role, shareToken } : null}
        />
      );
    }

    case "no_auth": {
      // P-R29 Fix-3 atomicity guard: ?gate=skip is legal ONLY for
      // reason: 'first_contact'. For 'google_mismatch' the gate must
      // re-render — the user reaches ?gate=skip only via the
      // clearIdentityAndSkip Server Action, which clears the stale
      // entry in the same response.
      const allowGateSkip = gateSkip && result.reason === "first_contact";
      if (!allowGateSkip) {
        return (
          <SignInOrSkipGate
            slug={slug}
            shareToken={shareToken}
            showId={result.showId}
            reason={result.reason}
          />
        );
      }
      let roster;
      try {
        roster = await loadRoster(result.showId);
      } catch {
        return (
          <TerminalFailure
            code="PICKER_RESOLVER_LOOKUP_FAILED"
            retryHref={`/show/${slug}/${shareToken}`}
          />
        );
      }
      return (
        <PickerInterstitial
          slug={slug}
          shareToken={shareToken}
          showId={result.showId}
          roster={roster}
          banner={null}
          staleCleanupHint={null}
        />
      );
    }

    case "epoch_stale":
    case "removed_from_roster":
    case "identity_invalidated": {
      let roster;
      try {
        roster = await loadRoster(result.showId);
      } catch {
        return (
          <TerminalFailure
            code="PICKER_RESOLVER_LOOKUP_FAILED"
            retryHref={`/show/${slug}/${shareToken}`}
          />
        );
      }
      const banner =
        result.kind === "epoch_stale"
          ? "PICKER_EPOCH_STALE_BANNER"
          : result.kind === "removed_from_roster"
            ? "PICKER_REMOVED_FROM_ROSTER_BANNER"
            : "PICKER_IDENTITY_CLAIMED_AFTER_PICK_BANNER";
      return (
        <PickerInterstitial
          slug={slug}
          shareToken={shareToken}
          showId={result.showId}
          roster={roster}
          banner={banner}
          staleCleanupHint={{
            expectedEpoch: result.expectedEpoch,
            expectedCrewMemberId: result.expectedCrewMemberId,
          }}
        />
      );
    }

    default: {
      // assertNever exhaustiveness — typeScript errors at compile time
      // if any new kind is added to ResolveShowPageAccessResult and
      // this switch doesn't handle it.
      const _exhaustive: never = result;
      return _exhaustive;
    }
  }
}
