/**
 * tests/app/admin/attentionModalGallery.serverProps.test.ts
 * (plan 2026-07-21-attention-modal-switcher-gallery Task 4)
 *
 * The server-side partition: which scenarios render in the switcher, which are
 * excluded and why. Three orthogonal axes — EXPRESSIBLE (the modal can reproduce
 * the placement), VISIBLE (the modal shows something), and SHOW-SCOPE REACHABLE
 * (a real show can actually hold the alert). All three exclusion sets are PINNED
 * to exact id lists so a catalog/derivation drift fails loudly instead of
 * silently adapting.
 */
import { describe, expect, test } from "vitest";
import {
  partitionScenarios,
  isModalExpressible,
  isModalVisible,
  isShowScopeReachable,
  resolveInitialScenario,
} from "@/app/admin/dev/attention-gallery/buildSwitcherScenarios";
import { deriveScenarioAttention } from "@/lib/dev/deriveScenarioAttention";
import { GLOBAL_SCOPE_CODES } from "@/lib/adminAlerts/alertScope";
import {
  T2_SECTION_ABSENT,
  T2_OVERVIEW_ABSENT,
  T2_CREW_ROW_ABSENT,
  T2_ANCHOR_ABSENT,
  T2_EMPTY,
  T2_DEGRADED,
  tier2Scenarios,
  T2_HOLD_ONLY,
  T2_MANY,
  T2_DEGRADED_WITH_HOLDS,
} from "@/lib/dev/attentionScenarios/tier2";
import { tier1AlertScenarios, tier1WarningScenarios } from "@/lib/dev/attentionScenarios/tier1";
import { T3_IDS, T3_CREW_COLLISION } from "@/lib/dev/attentionScenarios/tier3";
import { scenarioGroup } from "@/app/admin/dev/attention-gallery/buildSwitcherScenarios";
import { GROUP_ORDER } from "@/lib/dev/galleryModalTypes";
import { ALL_SCENARIOS, scenarioById } from "@/lib/dev/attentionScenarios/index";
import type { AttentionScenario } from "@/lib/dev/attentionScenarios/types";

const EXPECTED_STRUCTURAL = [T2_SECTION_ABSENT, T2_OVERVIEW_ABSENT, T2_CREW_ROW_ABSENT].sort();

// The exact cut set today (checked-in). A new/removed cut scenario must fail
// this pin, not silently adapt (cut-axis review finding 1).
const EXPECTED_CUT_IDS = [
  "alert-asset-recovery-drift-cooldown",
  "alert-asset-recovery-revision-drift",
  "alert-branch-protection-drift",
  "alert-branch-protection-monitor-auth-failed",
  "alert-callback-claim-threw",
  "alert-email-delivery-failed",
  "alert-email-not-configured",
  "alert-github-bot-login-missing",
  "alert-oauth-identity-claimed",
  "alert-pending-snapshot-delete-stuck",
  "alert-pending-snapshot-promote-stuck",
  "alert-pending-snapshot-rollback-stuck",
  "alert-picker-bootstrap-resolve-show-failed",
  "alert-picker-bootstrap-rpc-failed",
  "alert-picker-epoch-reset",
  "alert-picker-identity-claimed-tamper",
  "alert-picker-selection-race",
  "alert-report-duplicate-live-matches",
  "alert-report-lease-thrashing",
  "alert-report-lookup-inconclusive",
  "alert-report-open-orphan-label",
  "alert-report-orphaned-lost-lease",
  "alert-role-flags-notice",
  "alert-show-first-published",
  "alert-stale-orphan-report",
  "alert-tile-projection-fetch-failed",
  "alert-tile-server-render-failed",
  "alert-webhook-token-invalid",
  "alert-wizard-session-superseded-race",
].sort();

// The exact GLOBAL set today (checked-in, NOT derived from GLOBAL_SCOPE_CODES:
// deriving it from the constant the implementation reads would pass regardless
// of what the predicate or the partition actually does).
const EXPECTED_GLOBAL_IDS = [
  "alert-live-row-conflict",
  "alert-onboarding-sheet-unreadable",
  "alert-sync-stalled",
  "alert-watch-channel-orphaned",
].sort();

// partitionScenarios().rendered captured at b4603d58, BEFORE the global axis
// landed. Checked in verbatim rather than regenerated by calling the function
// under test. The post-change expectation is this list MINUS
// EXPECTED_GLOBAL_IDS and nothing else, so an unrelated scenario moving (or an
// accidental edit to isModalVisible) fails loudly.
//
// The gallery derives one scenario per catalog code, so a NEW warn code extends this
// baseline by construction — that is the intended fail-by-default, and each addition
// is a reviewed diff naming its spec. Added since the capture:
// warn-hotel-inline-group-own-hotel + warn-hotel-inline-group-hotel-suspected
// (docs/superpowers/specs/parser/2026-07-27-inline-later-group-own-hotel-design.md §6).
// Eleven more added 2026-08-03 by `chore/scanner-precision-cluster`
// (docs/superpowers/specs/2026-08-03-scanner-precision-cluster-design.md §2.4): these
// codes were always emitted and always in the §12.4 catalog, but the old scanner could
// not see the factories that build them, so the gallery never rendered them. They are
// recovered, not new — which is exactly the rot the guard now prevents.
// One more added 2026-08-09 by the parser mutation wave: warn-ref-error-literal
// (docs/superpowers/specs/parser/2026-08-07-parser-mutation-wave-design.md §4). A new
// warn-severity ParseWarning code renders a gallery scenario, so the baseline grows by
// exactly one — that is the reviewed diff naming its spec this list asks for.
// And one more from wave branch 3: warn-row-cells-fused (same spec, §5 — a data row one
// cell short of its section's modal width is how a merged cell exports). Same reasoning,
// same +1; the guard caught this addition rather than the branch remembering it, which is
// the fail-by-default working as designed.
// And one more from wave branch 4: warn-leading-column-autocorrected (same spec, §6 — every
// row a section owns leading with an empty cell is how a drag-shifted section exports).
// Same +1, and the guard caught this one too — on CI rather than locally, which is the
// note worth leaving: this file is the ONE consumer of a new warn code that lives outside
// `tests/parser`, `tests/messages`, and `tests/help`, so a branch that verifies only those
// three sees green and learns about the baseline from `unit-suite-nodb`.
const RENDERED_IDS_BEFORE: string[] = [
  "alert-ambiguous-email-binding",
  "alert-asset-recovery-bytes-exceeded",
  "alert-drive-fetch-failed",
  "alert-embedded-asset-drifted",
  "alert-embedded-recovery-requires-restage",
  "alert-live-row-conflict",
  "alert-onboarding-sheet-unreadable",
  "alert-opening-reel-not-video",
  "alert-opening-reel-permission-denied",
  "alert-parse-error-last-good",
  "alert-reel-drifted",
  "alert-resync-quality-regressed",
  "alert-resync-shrink-held",
  "alert-sheet-unavailable",
  "alert-show-unpublished",
  "alert-sync-stalled",
  "alert-watch-channel-orphaned",
  "t2-act-archive-notfound",
  "t2-act-archive-refusal",
  "t2-act-bulkignore-fail",
  "t2-act-bulkignore-partial",
  "t2-act-crewreset-notfound",
  "t2-act-feed-errors",
  "t2-act-pending",
  "t2-act-publish-generic",
  "t2-act-publish-refusal",
  "t2-act-resolve-error",
  "t2-act-resync-error",
  "t2-act-resync-shrink",
  "t2-act-resync-success",
  "t2-act-share-errors",
  "t2-act-share-success",
  "t2-actionable",
  "t2-agenda-overflow",
  "t2-alert-deep-link",
  "t2-all-ignored",
  "t2-anchor-absent",
  "t2-archived",
  "t2-attention-extras",
  "t2-auto-resolving",
  "t2-changelog-history",
  "t2-class-mix",
  "t2-crew-beyond-cap",
  "t2-degraded",
  "t2-degraded-with-holds",
  "t2-diagram-images",
  "t2-empty",
  "t2-feed-infra-error",
  "t2-feed-truncated",
  "t2-finalizing",
  "t2-hold-dispositions",
  "t2-hold-only",
  "t2-hotel-guest-stack",
  "t2-identity-absent",
  "t2-ignored-warnings",
  "t2-inbox-routed",
  "t2-live-now",
  "t2-many",
  "t2-minimal-header",
  "t2-monitoring-only",
  "t2-multi-agenda",
  "t2-multi-hold",
  "t2-never-synced",
  "t2-nothing-parsed",
  "t2-occurrence-many",
  "t2-overflow-volumes",
  "t2-packlist-overflow",
  "t2-publishing",
  "t2-roster-over-cap",
  "t2-share-batches",
  "t2-share-link",
  "t2-share-single",
  "t2-single",
  "t2-solo-hotel",
  "t2-sync-drive-error",
  "t2-sync-no-check",
  "t2-sync-not-yet",
  "t2-sync-parse-error",
  "t2-sync-pending",
  "t2-sync-pending-review",
  "t2-sync-sheet-unavailable",
  "t2-sync-shrink-held",
  "t2-sync-unknown",
  "t2-uncataloged",
  "t2-unpublished",
  "t2-warning-spread",
  "t3-crew-collision-with-warnings",
  "t3-full-attention-split",
  "t3-hold-pending-with-asset-drift",
  "t3-sheet-missing-mid-parse",
  "warn-agenda-block-unresolved",
  "warn-agenda-day-ambiguous",
  "warn-agenda-day-emptied",
  "warn-agenda-day-truncated",
  "warn-agenda-file-inaccessible",
  "warn-agenda-grid-malformed",
  "warn-agenda-link-not-clickable",
  "warn-agenda-pdf-unreadable",
  "warn-agenda-schedule-low-confidence",
  "warn-agenda-schedule-time-adjusted",
  "warn-block-disappeared",
  "warn-column-header-autocorrected",
  "warn-crew-column-positional-fallback",
  "warn-date-order-suggests-dmy",
  "warn-day-restriction-double-location",
  "warn-diagrams-embedded-cap-exceeded",
  "warn-diagrams-embedded-none-found",
  "warn-diagrams-embedded-object-inaccessible",
  "warn-diagrams-embedded-revisions-unavailable",
  "warn-diagrams-tab-missing",
  "warn-embedded-asset-drifted",
  "warn-embedded-recovery-requires-restage",
  "warn-field-label-autocorrected",
  "warn-field-unreadable",
  "warn-hotel-address-split-ambiguous",
  "warn-hotel-cardinality-exceeded",
  "warn-hotel-guest-split-ambiguous",
  "warn-hotel-inline-group-hotel-suspected",
  "warn-hotel-inline-group-own-hotel",
  "warn-leading-column-autocorrected",
  "warn-linked-folder-overflow-truncated",
  "warn-opening-reel-not-video",
  "warn-opening-reel-permission-denied",
  "warn-orphaned-crew-rows",
  "warn-pull-sheet-ambiguous-format",
  "warn-pull-sheet-on-archived-tab",
  "warn-pull-sheet-override-content-changed",
  "warn-pull-sheet-parse-partial",
  "warn-pull-sheet-unknown-variant",
  "warn-reel-drifted",
  "warn-ref-error-literal",
  "warn-role-token-autocorrected",
  "warn-room-header-split-ambiguous",
  "warn-row-cells-fused",
  "warn-schedule-strike-date-off-schedule",
  "warn-schedule-time-unparsed",
  "warn-section-header-autocorrected",
  "warn-section-header-no-fields",
  "warn-stage-word-autocorrected",
  "warn-travel-flight-ambiguous-table",
  "warn-travel-flight-name-unmatched",
  "warn-travel-flight-unparseable",
  "warn-travel-transport-name-unmatched",
  "warn-typo-normalized",
  "warn-unknown-day-restriction",
  "warn-unknown-field",
  "warn-unknown-role-token",
  "warn-unknown-section-header",
  "warn-unknown-stage-restriction",
  "warn-venue-geocode-unresolved",
  "warn-venue-timezone-unresolved",
];

function minimal(id: string, over: Partial<AttentionScenario> = {}): AttentionScenario {
  return { id, tier: 1, label: id, alerts: [], holds: [], ...over };
}

// Round-1 review returned BLOCKING on an earlier `every`-based predicate that
// kept a scenario whose alerts were only PARTLY global, on the theory that the
// carrier was "the real state under review". It is not: deriveScenarioAttention
// derives an item for EVERY declared alert and the modal renders it, so one
// global code makes the whole card fiction. The mixed and carrier rows below
// are the two assertions that fail under the rejected form.
const HOLD_ONLY_FIXTURE = {
  drive_file_id: "gallery-fixture-file",
  domain: "crew_email" as const,
  entity_key: "dana-reed",
  held_value: { email: "old@example.test" },
  proposed_value: {
    disposition: "email_change" as const,
    name: "Dana Reed",
    email: "new@example.test",
  },
  base_modified_time: "2026-07-01T12:00:00.000Z",
  kind: "mi11_pending" as const,
};

const alertRow = (code: string) => ({
  code,
  context: {},
  raised_at: "2026-07-01T12:00:00.000Z",
  occurrence_count: 1,
});

describe("isShowScopeReachable (synthetic truth table)", () => {
  test("no alerts is reachable", () => {
    expect(isShowScopeReachable(minimal("x"))).toBe(true);
  });

  test("a single global alert is NOT reachable", () => {
    expect(isShowScopeReachable(minimal("x", { alerts: [alertRow("LIVE_ROW_CONFLICT")] }))).toBe(
      false,
    );
  });

  test("two different global codes are NOT reachable", () => {
    expect(
      isShowScopeReachable(
        minimal("x", { alerts: [alertRow("SYNC_STALLED"), alertRow("WATCH_CHANNEL_ORPHANED")] }),
      ),
    ).toBe(false);
  });

  test("MIXED global plus per-show is NOT reachable", () => {
    expect(
      isShowScopeReachable(
        minimal("x", { alerts: [alertRow("SYNC_STALLED"), alertRow("DRIVE_FETCH_FAILED")] }),
      ),
    ).toBe(false);
  });

  test("a warning carrier does NOT rescue a global alert", () => {
    expect(
      isShowScopeReachable(
        minimal("x", {
          alerts: [alertRow("LIVE_ROW_CONFLICT")],
          warnings: [{ severity: "warn", code: "UNKNOWN_FIELD", message: "synthetic" }],
        }),
      ),
    ).toBe(false);
  });

  test("a fixture carrier does NOT rescue a global alert", () => {
    expect(
      isShowScopeReachable(
        minimal("x", { alerts: [alertRow("LIVE_ROW_CONFLICT")], fixture: { archived: true } }),
      ),
    ).toBe(false);
  });

  // R2 finding 3: the empty-alerts row above only covers a BARE scenario. A
  // broken predicate like `s.holds.length === 0 && !s.alerts.some(global)`
  // passes every assertion above while wrongly excluding the holds-only
  // scenario, so each non-alert carrier gets its own row.
  test("carrier-only scenarios stay reachable (no alerts to judge)", () => {
    const carriers: Array<[string, Partial<AttentionScenario>]> = [
      ["holds", { holds: [HOLD_ONLY_FIXTURE] }],
      ["warnings", { warnings: [{ severity: "warn", code: "UNKNOWN_FIELD", message: "x" }] }],
      ["degraded", { degraded: true }],
      ["feedNull", { feedNull: true }],
      ["feedTruncated", { feedTruncated: true }],
      [
        "changeLog",
        {
          changeLog: [
            {
              occurred_at: "2026-07-01T12:00:00.000Z",
              status: "applied",
              summary: "s",
              entity_ref: null,
              change_kind: "crew_email",
              individually_undoable: true,
              source: "auto_apply",
              acknowledged_at: null,
            },
          ],
        },
      ],
      ["fixture", { fixture: { archived: true } }],
      ["actionOutcomes", { actionOutcomes: {} }],
      ["bucket", { bucket: { sectionAvailable: () => false } }],
      ["landing", { landing: "overview" }],
    ];
    for (const [name, over] of carriers) {
      expect(isShowScopeReachable(minimal("x", over)), `${name}-only must stay reachable`).toBe(
        true,
      );
    }
  });

  test("a per-show alert PLUS every carrier is still reachable", () => {
    expect(
      isShowScopeReachable(
        minimal("x", {
          alerts: [alertRow("DRIVE_FETCH_FAILED")],
          holds: [HOLD_ONLY_FIXTURE],
          warnings: [{ severity: "warn", code: "UNKNOWN_FIELD", message: "x" }],
          degraded: true,
          fixture: { archived: true },
        }),
      ),
    ).toBe(true);
  });

  test("only per-show alerts is reachable", () => {
    expect(isShowScopeReachable(minimal("x", { alerts: [alertRow("DRIVE_FETCH_FAILED")] }))).toBe(
      true,
    );
  });

  test("an unknown code is reachable (fail toward VISIBLE)", () => {
    expect(isShowScopeReachable(minimal("x", { alerts: [alertRow("NOT_A_REAL_CODE")] }))).toBe(
      true,
    );
  });
});

describe("isModalExpressible (synthetic truth table)", () => {
  test("a sectionAvailable override is not expressible", () => {
    expect(isModalExpressible(minimal("x", { bucket: { sectionAvailable: () => false } }))).toBe(
      false,
    );
  });
  test("a crewKeyRendered override is not expressible", () => {
    expect(isModalExpressible(minimal("x", { bucket: { crewKeyRendered: () => false } }))).toBe(
      false,
    );
  });
  test("both overrides is not expressible", () => {
    expect(
      isModalExpressible(
        minimal("x", { bucket: { sectionAvailable: () => false, crewKeyRendered: () => true } }),
      ),
    ).toBe(false);
  });
  test("no override (or only anchorAvailable) is expressible", () => {
    expect(isModalExpressible(minimal("x"))).toBe(true);
    expect(isModalExpressible(minimal("x", { bucket: { anchorAvailable: () => false } }))).toBe(
      true,
    );
  });
});

describe("isModalVisible", () => {
  test("a surfacing alert scenario is visible", () => {
    const surfacing = tier1AlertScenarios().find((s) => deriveScenarioAttention(s).length > 0)!;
    expect(isModalVisible(surfacing)).toBe(true);
  });
  test("a cut alert scenario (declares an alert, derives nothing) is NOT visible", () => {
    const cut = tier1AlertScenarios().find(
      (s) => s.alerts.length > 0 && deriveScenarioAttention(s).length === 0,
    )!;
    expect(isModalVisible(cut)).toBe(false);
  });
  test("a warnings-only scenario is visible", () => {
    const warned = tier1WarningScenarios().find((s) => (s.warnings?.length ?? 0) > 0)!;
    expect(isModalVisible(warned)).toBe(true);
  });
  test("the intentional-empty baseline (declares no attention) is visible", () => {
    expect(isModalVisible(tier2Scenarios().find((s) => s.id === T2_EMPTY)!)).toBe(true);
  });
  test("a degraded scenario is visible", () => {
    expect(isModalVisible(tier2Scenarios().find((s) => s.id === T2_DEGRADED)!)).toBe(true);
  });
});

describe("partitionScenarios", () => {
  const { rendered, excluded } = partitionScenarios();

  test("structural excluded set is EXACTLY the three predicate-override ids, and all are visible", () => {
    const structural = excluded.filter((e) => e.reason === "structural");
    expect(structural.map((e) => e.id).sort()).toEqual(EXPECTED_STRUCTURAL);
    for (const id of EXPECTED_STRUCTURAL) {
      const s = tier2Scenarios().find((x) => x.id === id)!;
      expect(isModalVisible(s), `${id} should be structural-only (visible)`).toBe(true);
    }
  });

  test("global excluded set is EXACTLY the four checked-in ids", () => {
    const global = excluded.filter((e) => e.reason === "global");
    expect(global.map((e) => e.id).sort()).toEqual(EXPECTED_GLOBAL_IDS);
  });

  test("the six health-audience global codes keep their CUT label (ordering contract)", () => {
    // The global arm runs AFTER cut on purpose. Evaluating it first would
    // relabel these six and churn EXPECTED_CUT_IDS for no benefit.
    for (const id of [
      "alert-picker-identity-claimed-tamper",
      "alert-webhook-token-invalid",
      "alert-callback-claim-threw",
      "alert-github-bot-login-missing",
      "alert-picker-bootstrap-rpc-failed",
      "alert-picker-bootstrap-resolve-show-failed",
    ]) {
      expect(EXPECTED_CUT_IDS, id).toContain(id);
      expect(excluded.find((e) => e.id === id)?.reason, `${id} must stay cut, not global`).toBe(
        "cut",
      );
    }
  });

  test("NO tier-2 or tier-3 scenario declares a global-scope code", () => {
    // Tier 1 is the one-card-per-route-key fan-out, so a global code there is
    // expected and handled by the partition. A COMPOSITE is different: it uses
    // codes as ingredients to demonstrate a structural state, so a global one
    // would make it teach a state production cannot produce — and the partition
    // would drop the whole composite, taking its per-show alerts, holds, and
    // sections with it. Every tier-2 picker filters GLOBAL_SCOPE_CODES; this
    // walks the catalogue so a NEW composite fails here by default.
    const offenders = ALL_SCENARIOS.filter((sc) => sc.tier !== 1).flatMap((sc) =>
      sc.alerts.filter((a) => GLOBAL_SCOPE_CODES.has(a.code)).map((a) => `${sc.id}: ${a.code}`),
    );
    expect(offenders).toEqual([]);
  });

  test("no COMPOSITE is excluded as global (the guard above holds end to end)", () => {
    const composites = excluded.filter((e) => e.reason === "global" && !e.id.startsWith("alert-"));
    expect(composites.map((e) => e.id)).toEqual([]);
  });

  test("NO tier-1 scenario for a global-scope code renders", () => {
    const renderedTier1Global = rendered.filter(
      (sc) => sc.tier === 1 && sc.codes.some((c) => GLOBAL_SCOPE_CODES.has(c)),
    );
    expect(renderedTier1Global.map((sc) => sc.id)).toEqual([]);
  });

  test("no scenario is excluded under two reasons", () => {
    const ids = excluded.map((e) => e.id);
    expect(ids.filter((v, i) => ids.indexOf(v) !== i)).toEqual([]);
  });

  test("rendered is the pre-change baseline minus EXACTLY the four global ids", () => {
    expect(rendered.map((s) => s.id).sort()).toEqual(
      RENDERED_IDS_BEFORE.filter((id) => !EXPECTED_GLOBAL_IDS.includes(id)),
    );
  });

  test("cut excluded set is EXACTLY the checked-in id list (drift fails the pin)", () => {
    const cut = excluded.filter((e) => e.reason === "cut");
    expect(cut.map((e) => e.id).sort()).toEqual(EXPECTED_CUT_IDS);
  });

  test("tiers 1-3 all render; T2_ANCHOR_ABSENT and T2_EMPTY do render", () => {
    expect(rendered.every((s) => s.tier === 1 || s.tier === 2 || s.tier === 3)).toBe(true);
    expect(rendered.some((s) => s.id === T2_ANCHOR_ABSENT)).toBe(true);
    expect(rendered.some((s) => s.id === T2_EMPTY)).toBe(true);
  });

  test("renders every tier-3 composite", () => {
    for (const id of T3_IDS) {
      expect(
        rendered.some((s) => s.id === id),
        id,
      ).toBe(true);
      expect(
        excluded.some((e) => e.id === id),
        id,
      ).toBe(false);
    }
  });

  test("integration visibility: every rendered scenario shows something (no blank modal)", () => {
    for (const s of rendered) {
      const d = s.data;
      const hasItem = d.attentionItems.length > 0;
      const hasWarning = Object.keys(d.bySection ?? {}).length > 0;
      const isDegraded = d.alertsDegraded === true;
      const isCleanBaseline = d.attentionItems.length === 0; // T2_EMPTY-class clean modal
      expect(hasItem || hasWarning || isDegraded || isCleanBaseline, `${s.id} blank`).toBe(true);
    }
  });

  test("every rendered scenario's data is serializable", () => {
    for (const s of rendered) expect(() => structuredClone(s.data)).not.toThrow();
  });

  test("codes are carried server-side", () => {
    const withAlert = rendered.find((s) => s.codes.length > 0)!;
    expect(withAlert.codes.length).toBeGreaterThan(0);
  });

  test("groups derive from the real routers", () => {
    expect(scenarioGroup(scenarioById(T2_EMPTY)!)).toBe("baseline");
    expect(scenarioGroup(scenarioById(T2_DEGRADED)!)).toBe("baseline");
    expect(scenarioGroup(scenarioById(T2_HOLD_ONLY)!)).toBe("changes");
    expect(scenarioGroup(scenarioById(T2_DEGRADED_WITH_HOLDS)!)).toBe("changes");
    expect(scenarioGroup(scenarioById(T2_MANY)!)).toBe("mixed");
    expect(scenarioGroup(scenarioById("alert-sync-stalled")!)).toBe("overview");
    expect(scenarioGroup(scenarioById(T3_CREW_COLLISION)!)).toBe("mixed");
  });

  test("rendered list is group-sorted, stable within groups, every scenario stamped", () => {
    const orders = rendered.map((s) => GROUP_ORDER.indexOf(s.group));
    expect(orders).toEqual([...orders].sort((a, b) => a - b));
    expect(orders.every((o) => o >= 0)).toBe(true);
  });
});

describe("resolveInitialScenario", () => {
  const { rendered } = partitionScenarios();
  const validId = rendered[0]!.id;

  test("valid scalar resolves; unknown/excluded/tier3/empty/undefined -> null", () => {
    expect(resolveInitialScenario(validId, rendered)).toBe(validId);
    expect(resolveInitialScenario("nope", rendered)).toBeNull();
    expect(resolveInitialScenario(T2_SECTION_ABSENT, rendered)).toBeNull(); // structural excluded
    expect(resolveInitialScenario("alert-email-delivery-failed", rendered)).toBeNull(); // cut excluded
    expect(resolveInitialScenario("", rendered)).toBeNull();
    expect(resolveInitialScenario(undefined, rendered)).toBeNull();
  });

  test("array normalization: first wins; unknown-first does NOT fall through; empty -> null", () => {
    expect(resolveInitialScenario([validId, "x"], rendered)).toBe(validId);
    expect(resolveInitialScenario(["nope", validId], rendered)).toBeNull();
    expect(resolveInitialScenario([], rendered)).toBeNull();
  });
});

// ── Modal-state-coverage: visibility carriers, grouping fallbacks, shareToken ──
// (plan Task 5)

describe("isModalVisible - modal-state carriers", () => {
  const cutAlert = {
    code: "PICKER_EPOCH_RESET",
    context: {},
    raised_at: "2026-07-01T11:00:00.000Z",
    occurrence_count: 1,
  };
  test("a cut-only alert alone stays excluded", () => {
    expect(isModalVisible(minimal("t2-msc-cut", { tier: 2, alerts: [cutAlert] }))).toBe(false);
  });
  test("feedNull, non-empty changeLog, and an effective fixture each make it visible", () => {
    expect(
      isModalVisible(minimal("t2-msc-v1", { tier: 2, alerts: [cutAlert], feedNull: true })),
    ).toBe(true);
    expect(
      isModalVisible(
        minimal("t2-msc-v2", {
          tier: 2,
          alerts: [cutAlert],
          changeLog: [
            {
              occurred_at: "2026-07-01T10:00:00.000Z",
              status: "applied",
              summary: "x",
              entity_ref: null,
              change_kind: "field_changed",
              individually_undoable: false,
              source: "auto_apply",
              acknowledged_at: null,
            },
          ],
        }),
      ),
    ).toBe(true);
    expect(
      isModalVisible(
        minimal("t2-msc-v3", {
          tier: 2,
          alerts: [cutAlert],
          fixture: { archived: true, published: false },
        }),
      ),
    ).toBe(true);
  });
});

describe("scenarioGroup - landing and rendered-section fallbacks", () => {
  test("fixture-only scenario with landing groups there; landing loses to real sections", () => {
    expect(
      scenarioGroup(
        minimal("t2-msc-g1", {
          tier: 2,
          fixture: { archived: true, published: false },
          landing: "overview",
        }),
      ),
    ).toBe("overview");
    const withHold = scenarioById("t2-hold-only");
    expect(withHold).toBeDefined();
    expect(scenarioGroup({ ...withHold!, landing: "overview" })).toBe("changes");
  });
  test("agenda-routed warning + empty agenda groups under warnings (rendered-section fallback)", () => {
    const s = minimal("t2-msc-g2", {
      tier: 2,
      warnings: [
        {
          severity: "warn",
          code: "AGENDA_SCHEDULE_LOW_CONFIDENCE",
          message: "Synthetic warning for gallery review.",
          blockRef: { kind: "agenda" },
        },
      ],
      fixture: { empty: ["agenda"] },
    });
    expect(scenarioGroup(s)).toBe("warnings");
  });
  test("anchor-absent alert groups under overview (modal redirect parity)", () => {
    const anchorAbsent = scenarioById(T2_ANCHOR_ABSENT);
    expect(anchorAbsent).toBeDefined();
    expect(scenarioGroup(anchorAbsent!)).toBe("overview");
  });
});

describe("partitionScenarios - shareToken stamping", () => {
  test("share scenarios carry a token; others null", () => {
    const { rendered } = partitionScenarios();
    for (const sc of rendered) {
      const source = scenarioById(sc.id);
      const wantsShare = source?.fixture?.share?.linkActive === true;
      if (wantsShare) expect(sc.shareToken, sc.id).toEqual(expect.any(String));
      else expect(sc.shareToken, sc.id).toBeNull();
    }
  });
});

describe("actionOutcomes passthrough (spec 2026-07-23 §3.1)", () => {
  test("a scripted-only tier-2 scenario is visible and its script survives partition verbatim", () => {
    const scripted: AttentionScenario = {
      id: "t2-passthrough-probe",
      tier: 2,
      label: "probe",
      alerts: [],
      holds: [],
      landing: "actions",
      actionOutcomes: { resync: { kind: "pending" } },
    };
    // Carrier contract: actionOutcomes alone must make the modal visible
    // (failure mode: scripted-only scenarios silently excluded).
    expect(isModalVisible(scripted)).toBe(true);
  });

  test("rendered entries carry actionOutcomes verbatim or null", () => {
    const { rendered } = partitionScenarios();
    for (const r of rendered) {
      const src = scenarioById(r.id);
      expect(r.actionOutcomes, r.id).toEqual(src?.actionOutcomes ?? null);
    }
    // At least the roster's scripted scenarios must be non-null once Task 7 lands;
    // until then this pins the null default end-to-end.
    expect(
      rendered.every((r) => r.actionOutcomes === null || typeof r.actionOutcomes === "object"),
    ).toBe(true);
  });
});
