import { describe, it, expect, afterEach } from "vitest";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { writeDevPanelPresent } from "../../scripts/with-admin-dev-flag.mjs";

const DEV_PANEL_FILE = join(process.cwd(), "lib/admin/__generated__/devPanelPresent.ts");

const COMMITTED_DEFAULT = `// GENERATED by scripts/with-admin-dev-flag.mjs at build time; committed value is the
// fail-closed default. The build tool overwrites this to match ADMIN_DEV_PANEL_ENABLED
// before \`next build\` and restores \`false\` on exit (clean working tree).
export const DEV_PANEL_PRESENT = false;
`;

afterEach(() => {
  // Always leave the committed fail-closed default on disk (clean working tree).
  writeFileSync(DEV_PANEL_FILE, COMMITTED_DEFAULT);
});

describe("writeDevPanelPresent", () => {
  it("writes DEV_PANEL_PRESENT = true when enabled", () => {
    writeDevPanelPresent(true);
    const content = readFileSync(DEV_PANEL_FILE, "utf8");
    expect(content).toContain("export const DEV_PANEL_PRESENT = true;");
    expect(content).toContain("// GENERATED by scripts/with-admin-dev-flag.mjs");
  });

  it("writes DEV_PANEL_PRESENT = false when disabled (restore default)", () => {
    writeDevPanelPresent(true);
    writeDevPanelPresent(false);
    const content = readFileSync(DEV_PANEL_FILE, "utf8");
    expect(content).toContain("export const DEV_PANEL_PRESENT = false;");
  });
});
