// @generated by scripts/generate-admin-tables.ts; do not edit.
// Source: docs/superpowers/specs/2026-04-30-fxav-crew-pages-design.md §4.3 admin-only tables.
// Count: 21 tables.
export const ADMIN_TABLES: readonly string[] = [
  "shows_internal",
  "sync_log",
  "reports",
  "pending_syncs",
  "pending_ingestions",
  "crew_member_auth",
  "revoked_links",
  "link_sessions",
  "bootstrap_nonces",
  "app_settings",
  "deferred_ingestions",
  "admin_alerts",
  "sync_audit",
  "drive_watch_channels",
  "report_rate_limits",
  "onboarding_scan_manifest",
  "pending_snapshot_uploads",
  "revision_race_cooldowns",
  "wizard_finalize_checkpoints",
  "shows_pending_changes",
  "recovery_drift_cooldowns",
] as const;
