// @generated by scripts/extract-watermark-symbols.ts; do not edit.
// Source: docs/superpowers/specs/2026-04-30-fxav-crew-pages-design.md §17.2 AC-X.4.
// Counts: 15 gating watermarks; 5 display-only timestamps; 8 sync entry points.
export const AUTHORITATIVE_GATING_WATERMARKS: ReadonlySet<string> = new Set([
  "shows.last_seen_modified_time",
  "pending_syncs.base_modified_time",
  "shows.diagrams->>snapshot_revision_id",
  "pending_syncs.staged_modified_time",
  "pending_syncs.staged_id",
  "fileMeta.modifiedTime",
  "fileMeta.driveModifiedTime",
  "fileMeta.headRevisionId",
  "fileMeta.md5Checksum",
  "deferred_ingestions.deferred_at_modified_time",
  "drive_watch_channels.expires_at",
  "drive_watch_channels.activated_at",
  "drive_watch_channels.superseded_at",
  "drive_watch_channels.stopped_at",
  "drive_watch_channels.created_at",
] as const);

export const DISPLAY_ONLY_TIMESTAMPS: ReadonlySet<string> = new Set([
  "shows.last_synced_at",
  "pending_syncs.parsed_at",
  "pending_ingestions.last_attempt_at",
  "pending_ingestions.first_seen_at",
  "deferred_ingestions.deferred_at",
] as const);

export const SYNC_ENTRY_POINTS: ReadonlySet<string> = new Set([
  "runScheduledCronSync",
  "runManualSyncForShow",
  "runPushSyncForShow",
  "runOnboardingScan",
  "retrySingleFile",
  "assetRecovery",
  "applyStagedParse",
  "discardStagedParse",
] as const);

export const BANNED_COMBOS: readonly (readonly string[])[] = [
  ["last", "watermark"],
  ["global", "watermark"],
  ["last", "cursor"],
  ["global", "cursor"],
  ["last", "poll"],
  ["last", "sync", "at"],
  ["last", "run"],
  ["last", "processed"],
  ["watermark", "at"],
  ["cursor", "at"],
  ["app", "watermark"],
  ["app", "cursor"],
] as const;

