/**
 * Probe: WHY do 17 mutation sites newly survive silently after the field near-miss detector?
 *
 * The harness's `newHoles` bucket carries a hard instruction — "do NOT re-bless, investigate
 * the parser change that stopped catching these mutants" (`mutationHarness.shard*.test.ts:50`).
 * The ledger is the authoritative PRE-arc measurement: a site absent from `RAW_HOLES` at
 * `origin/main` did not alarm before, by construction. So the open question is not WHETHER these
 * are new; it is the MECHANISM. This probe answers it per site, on the live tree.
 *
 * For each named site it prints the verdict, the baseline vs mutant warning-code multisets, and
 * the codes that the mutation REMOVED versus ADDED. The claim under test is narrow and falsifiable:
 * every one of these sites lost `UNKNOWN_FIELD` and nothing else, i.e. the only signal the old
 * parser raised on that mutation came from the positional venue sweep this arc deleted. Any site
 * that lost some OTHER code, or that lost nothing at all, refutes the claim and is a genuine parser
 * regression to fix rather than a ledger row to write.
 *
 * usage: pnpm exec tsx docs/superpowers/specs/parser/probes/2026-08-16-newhole-mechanism-probe.ts
 */
import { boundedMutants } from "@/tests/parser/mutation/operators";
import { capture, verdict } from "@/tests/parser/mutation/oracle";
import { FIXTURES, readFixture } from "@/tests/parser/mutation/fixtures";

/** The 17 `newHoles` keys from the 2026-08-16 collected run, reconciled against `d3bbabeda`. */
const NEW_HOLES = [
  "blank-row:remove:2024-05-east-coast-family-office:B7:L82:Xgap",
  "blank-row:remove:2025-05-redefining-fixed-income-private-credit:B1:L26:Xgap",
  "header-typo:2025-10-fixed-income-trading-summit:B5:L37:X0",
  "header-typo:2025-10-fixed-income-trading-summit:B9:L76:X0",
  "section-reorder:2024-05-east-coast-family-office:B0:L0:Xpair0",
  "header-typo:2026-03-rpas-central-four-seasons:B10:L96:X0",
  "blank-row:remove:east-coast:B9:L59:Xgap",
  "header-typo:2024-05-east-coast-family-office:B2:L12:X0",
  "header-typo:2024-05-east-coast-family-office:B3:L16:X0",
  "blank-row:remove:2025-10-consultants-roundtable:B3:L37:Xgap",
  "blank-row:remove:2025-04-asset-mgmt-cfo-coo:B2:L36:Xgap",
  "header-typo:2026-05-fintech-forum-cto-summit:B9:L81:X0",
  "blank-row:remove:2025-03-dci-rpas-central:B14:L314:Xgap",
  "blank-row:remove:2025-06-ria-investment-forum:B9:L235:Xgap",
  "header-typo:2025-10-consultants-roundtable:B27:L173:X0",
  "header-typo:2025-10-consultants-roundtable:B38:L249:X0",
  "header-typo:2025-10-consultants-roundtable:B39:L250:X0",
];

/** `runShard.withSlug`'s key shape, inverted: "<op>:<slug>:<rest>" with op containing ':'. */
function splitSiteId(siteId: string): { op: string; slug: string; rest: string } {
  for (const op of ["blank-row:remove", "blank-row:inject", "header-typo", "section-reorder"]) {
    if (siteId.startsWith(op + ":")) {
      const tail = siteId.slice(op.length + 1);
      const cut = tail.indexOf(":B");
      return { op, slug: tail.slice(0, cut), rest: tail.slice(cut + 1) };
    }
  }
  throw new Error(`unrecognized operator prefix in ${siteId}`);
}

const codesOf = (p: ReturnType<typeof capture>): string[] =>
  (p.warnings ?? []).map((w) => w.code).sort();

const multisetDiff = (from: string[], to: string[]): string[] => {
  const remaining = [...to];
  const gone: string[] = [];
  for (const c of from) {
    const i = remaining.indexOf(c);
    if (i === -1) gone.push(c);
    else remaining.splice(i, 1);
  }
  return gone;
};

let refuted = 0;
for (const key of NEW_HOLES) {
  const { op, slug, rest } = splitSiteId(key);
  const fixture = FIXTURES.find((f) => f.slug === slug);
  if (!fixture) {
    console.log(`${key}\n  NO FIXTURE for slug ${slug}`);
    refuted++;
    continue;
  }
  const md = readFixture(fixture);
  const wantSiteId = `${op}:${rest}`;
  let found = false;
  for (const m of boundedMutants(op, md)) {
    if (m.siteId !== wantSiteId) continue;
    found = true;
    const b = capture(md, `${slug}.md`);
    const mu = capture(m.md, `${slug}.md`);
    const bc = codesOf(b);
    const mc = codesOf(mu);
    const removed = multisetDiff(bc, mc);
    const added = multisetDiff(mc, bc);
    const onlyUnknownField = removed.length > 0 && removed.every((c) => c === "UNKNOWN_FIELD");
    if (!onlyUnknownField || added.length > 0) refuted++;
    console.log(
      [
        key,
        `  verdict:  ${verdict(b, mu)}`,
        `  removed:  ${removed.length ? removed.join(", ") : "(none)"}`,
        `  added:    ${added.length ? added.join(", ") : "(none)"}`,
        `  claim:    ${onlyUnknownField && added.length === 0 ? "HOLDS" : "REFUTED"}`,
      ].join("\n"),
    );
    break;
  }
  if (!found) {
    console.log(`${key}\n  SITE NOT GENERATED by ${op} on ${slug}`);
    refuted++;
  }
}

console.log(`\nSUMMARY ${NEW_HOLES.length - refuted}/${NEW_HOLES.length} hold, ${refuted} refuted`);
