/**
 * tests/infra/tailwindVersionParity.test.ts
 *
 * The harness CSS is built by `@tailwindcss/cli` while the app is built by
 * `tailwindcss`. If those drift apart, harness stylesheets are generated by a
 * different engine than the one that renders production — and the failure
 * shows up as an inexplicable layout assertion, not as a version error.
 *
 * Pinning alone does not prevent this: `@tailwindcss/cli` is pinned exactly,
 * but `tailwindcss` is a RANGE (`^4`), so an install can satisfy the manifest
 * while resolving a different minor. This asserts the RESOLVED versions, which
 * is the only form that can observe that (see
 * `feedback_structural_guards_assert_resolved_config`).
 */
import { createRequire } from "node:module";

import { describe, expect, it } from "vitest";

const require_ = createRequire(import.meta.url);

/** "4.2.4" -> "4.2" */
function majorMinor(version: string): string {
  return version.split(".").slice(0, 2).join(".");
}

describe("tailwind toolchain version parity", () => {
  it("resolves @tailwindcss/cli and tailwindcss to the same major.minor", () => {
    const cli = require_("@tailwindcss/cli/package.json") as { version: string };
    const core = require_("tailwindcss/package.json") as { version: string };

    expect(
      majorMinor(cli.version),
      `@tailwindcss/cli ${cli.version} and tailwindcss ${core.version} disagree; ` +
        "harness CSS would be generated by a different engine than the app uses",
    ).toBe(majorMinor(core.version));
  });

  it("pins @tailwindcss/cli exactly, so the resolved version cannot drift alone", () => {
    const manifest = require_("../../package.json") as {
      devDependencies: Record<string, string>;
    };
    const declared = manifest.devDependencies["@tailwindcss/cli"];

    expect(declared, "@tailwindcss/cli must be a devDependency").toBeDefined();
    expect(declared, "must be an exact pin, not a range").toMatch(/^\d+\.\d+\.\d+$/);
  });
});
