import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { walkSourceFiles } from "@/lib/messages/__internal__/walkSourceFiles";

export type InternalCodeEnumPayload = {
  source: string;
};

export type InternalCodeEnums = Record<string, InternalCodeEnumPayload>;

const OUTPUT_PATH = "lib/messages/__generated__/internal-code-enums.ts";
const CODE_RE = /^[A-Z][A-Za-z0-9_-]*(?:_[A-Za-z0-9_-]+)+$/;
const CODE_LITERAL_RE = /["'`]([A-Z][A-Za-z0-9_-]*(?:_[A-Za-z0-9_-]+)+)["'`]/g;
const CODE_PROPERTY_RE = /\bcode\s*:\s*["'`]([A-Z][A-Za-z0-9_-]*(?:_[A-Za-z0-9_-]+)+)["'`]/g;
const CONST_CODE_RE =
  /\b(?:export\s+)?const\s+[A-Z][A-Z0-9_]*\s*=\s*["'`]([A-Z][A-Za-z0-9_-]*(?:_[A-Za-z0-9_-]+)+)["'`]/g;
const FAILED_CODES_PUSH_RE =
  /\bfailedCodes\.push\(\s*["'`]([A-Z][A-Za-z0-9_-]*(?:_[A-Za-z0-9_-]+)+)["'`]\s*\)/g;
const LAST_SYNC_STATUS_VALUES = new Set([
  "ok",
  "drive_error",
  "sheet_unavailable",
  "parse_error",
  "pending_review",
]);

function add(
  out: Map<string, Set<string>>,
  code: string,
  source: string,
): void {
  if (!code) return;
  const sources = out.get(code) ?? new Set<string>();
  sources.add(source);
  out.set(code, sources);
}

function addCodeLiteralsFromSource(
  out: Map<string, Set<string>>,
  sourceText: string,
  provenance: string,
  regex = CODE_LITERAL_RE,
): void {
  for (const match of sourceText.matchAll(regex)) {
    const code = match[1];
    if (code && CODE_RE.test(code)) add(out, code, provenance);
  }
}

function readFiles(roots: readonly string[]): Array<{ path: string; source: string }> {
  return walkSourceFiles(roots)
    .filter((path) => !path.startsWith("lib/messages/__generated__/"))
    .filter((path) => path !== "lib/messages/catalog.ts")
    .map((path) => ({ path, source: readFileSync(path, "utf8") }));
}

function stableObjectLiteral(entries: InternalCodeEnums): string {
  return JSON.stringify(
    Object.fromEntries(Object.entries(entries).sort(([a], [b]) => a.localeCompare(b))),
    null,
    2,
  ).replace(/"([A-Za-z_$][A-Za-z0-9_$]*)":/g, "$1:");
}

export function extractInternalCodeEnums(): InternalCodeEnums {
  const out = new Map<string, Set<string>>();

  for (const { source } of readFiles(["lib/parser"])) {
    if (/\bParseWarning\b|\bwarnings\b|hardErrors/.test(source)) {
      addCodeLiteralsFromSource(out, source, "parse_warnings.code", CODE_PROPERTY_RE);
    }
  }

  for (const { source } of readFiles(["supabase/migrations", "lib/sync", "app/api"])) {
    for (const status of LAST_SYNC_STATUS_VALUES) {
      if (source.includes(status)) add(out, status, "shows.last_sync_status");
    }
  }

  for (const { source } of readFiles(["lib/parser", "lib/sync", "lib/onboarding", "app/api/admin"])) {
    if (
      /\blast_error_code\b|hardErrors|pending_ingestions|still_failed|staged_parse/i.test(source)
    ) {
      addCodeLiteralsFromSource(out, source, "pending_ingestions.last_error_code", CODE_PROPERTY_RE);
      addCodeLiteralsFromSource(
        out,
        source,
        "pending_ingestions.last_error_code",
        FAILED_CODES_PUSH_RE,
      );
      addCodeLiteralsFromSource(out, source, "pending_ingestions.last_error_code", CONST_CODE_RE);
    }
  }

  for (const { source } of readFiles(["lib", "app/api"])) {
    if (/\badmin_alerts?\b|upsertAdminAlert|upsert_admin_alert/i.test(source)) {
      addCodeLiteralsFromSource(out, source, "admin_alerts.code", CODE_PROPERTY_RE);
      addCodeLiteralsFromSource(out, source, "admin_alerts.code", CONST_CODE_RE);
    }
  }

  return Object.fromEntries(
    [...out.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([code, sources]) => [code, { source: [...sources].sort().join(",") }]),
  );
}

export function renderInternalCodeEnums(entries: InternalCodeEnums): string {
  return [
    "// Generated by scripts/extract-internal-code-enums.ts. Do not edit by hand.",
    "",
    "export type InternalCodeEnumPayload = {",
    "  source: string;",
    "};",
    "",
    `export const INTERNAL_CODE_ENUMS = ${stableObjectLiteral(entries)} as const satisfies Record<string, InternalCodeEnumPayload>;`,
    "",
    "export type InternalCodeEnum = keyof typeof INTERNAL_CODE_ENUMS;",
    "",
  ].join("\n");
}

export function writeInternalCodeEnums(outputPath = OUTPUT_PATH): void {
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, renderInternalCodeEnums(extractInternalCodeEnums()));
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeInternalCodeEnums();
}
