/**
 * scripts/gen-plan-fences-baseline.ts — regenerate the shrink-only baseline.
 *
 * Separate from the gate deliberately: a gate that can rewrite its own baseline
 * is a gate that passes by rewriting its own baseline.
 *
 * AND SEPARATION ALONE WAS NOT ENOUGH. The first version regenerated the rows
 * AND both "frozen" ceilings from whatever the corpus currently held, so the
 * documented shrink-only contract was a convention a reviewer had to enforce by
 * reading. The surviving mutant was two commands long: add a violation, run the
 * generator, commit — the new row and the raised ceilings land together and
 * every assertion stays green (diff review R1 finding 2).
 *
 * This script now REFUSES to raise either ceiling. Shrinking is free; growing
 * requires deleting the committed file outright, which is a deliberate,
 * review-visible act rather than a rerun.
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { analyzePlan } from "../lib/planFences";

const ROOT = "docs/superpowers/plans";
const OUT = "tests/docs/planFencesBaseline.ts";

function markdownFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    if (statSync(p).isDirectory()) out.push(...markdownFiles(p));
    else if (entry.endsWith(".md")) out.push(p);
  }
  return out.sort();
}

const priorSrc = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
const priorRows = Number(/export const FROZEN_ROWS = (\d+);/.exec(priorSrc)?.[1] ?? Infinity);
const priorTotal = Number(/export const FROZEN_TOTAL = (\d+);/.exec(priorSrc)?.[1] ?? Infinity);

const rows: string[] = [];
let total = 0;
for (const file of markdownFiles(ROOT)) {
  const report = analyzePlan(file, readFileSync(file, "utf8"));
  for (const f of report.findings) {
    // Identity is the fence's CONTENT digest, never its line number: a blank
    // line inserted above it must not invalidate the row.
    rows.push(`${f.path}|${f.fenceKey}|${f.rule}|${f.instance}|${f.count}`);
    total += f.count;
  }
}
rows.sort();

if (rows.length > priorRows || total > priorTotal) {
  console.error(
    `refusing to raise the baseline: rows ${priorRows} -> ${rows.length}, ` +
      `total ${priorTotal} -> ${total}.\n` +
      "The baseline is shrink-only. New violations are fixed or waived, not frozen.\n" +
      "If a raise is genuinely intended, delete the committed baseline first — that " +
      "makes it a visible, reviewable act rather than a rerun.",
  );
  process.exit(1);
}

const header = `/**
 * tests/docs/planFencesBaseline.ts — GENERATED. Frozen legacy plan-fence hits.
 *
 * Generated by \`pnpm tsx scripts/gen-plan-fences-baseline.ts\` at arc B G1b.
 * Do not hand-edit to ADD a row. The file exists so a new gate can ship without
 * rewriting hundreds of historical plans, which is churn with no product value.
 *
 * CONTRACT — the ratchet, stated at its true strength:
 *   (a) a corpus hit not matching a row within its count ALWAYS fails, so no new
 *       violation ever passes unlisted;
 *   (b) a stale row fails, so a repaired fence must shed its row in the same
 *       commit;
 *   (c) FROZEN_ROWS and FROZEN_TOTAL below are DECREASE-ONLY. Two ceilings, not
 *       one: a row count cannot see a count bump on an existing row, and a total
 *       cannot see a row split.
 *
 * What this deliberately does NOT claim: an identity SWAP — one row removed and
 * another added in a single edit — holds both totals and is not machine-
 * distinguishable from history. That needs a deliberate two-sided edit, which is
 * outside the accidental-authoring threat model and review-visible by
 * construction (spec §4 limit 3).
 *
 * A baseline row is a frozen defect in a historical document. It is not an
 * endorsement.
 */

/** Row format: \`path|fenceLine|RULE|instance|count\`. */
export const PLAN_FENCE_BASELINE: readonly string[] = [
${rows.map((r) => `  ${JSON.stringify(r)},`).join("\n")}
];

/** Decrease-only. Raising either is a deliberate, reviewed edit. */
export const FROZEN_ROWS = ${rows.length};
export const FROZEN_TOTAL = ${total};
`;

writeFileSync(OUT, header);
console.log(`wrote ${OUT}: ${rows.length} rows, ${total} total occurrences`);
