import { readFileSync, writeFileSync } from "node:fs";

const SPEC_PATH = "docs/superpowers/specs/2026-04-30-fxav-crew-pages-v1.md";
const OUT_PATH = "lib/audit/admin-tables.generated.ts";

function uniqueInOrder(values: readonly string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const value of values) {
    if (!seen.has(value)) {
      seen.add(value);
      out.push(value);
    }
  }
  return out;
}

export function extractAdminTablesFromSpec(spec: string): string[] {
  const showsInternal = spec.match(/- \*\*`(shows_internal)`:\s*admin-only/);
  const adminLine = spec
    .split(/\r?\n/)
    .find((line) => line.startsWith("- **Admin-only tables"));
  if (!showsInternal || !adminLine) {
    throw new Error("Could not find §4.3 admin-only table prose in spec");
  }

  const names = [
    showsInternal[1],
    ...Array.from(adminLine.matchAll(/`([a-z][a-z0-9_]*)`/g), (match) => match[1]),
  ].filter((name): name is string => typeof name === "string");
  const tableDefinitions = new Set(
    Array.from(spec.matchAll(/create table ([a-z][a-z0-9_]*)/g), (match) => match[1]),
  );
  const removedByPickerPivot = new Set([
    "crew_member_auth",
    "revoked_links",
    "link_sessions",
    "bootstrap_nonces",
  ]);
  return uniqueInOrder(names).filter(
    (name) => tableDefinitions.has(name) && name !== "shows" && !removedByPickerPivot.has(name),
  );
}

function render(tables: readonly string[]): string {
  const rows = tables.map((table) => `  ${JSON.stringify(table)},`).join("\n");
  return [
    "// @generated by scripts/generate-admin-tables.ts; do not edit.",
    "// Source: docs/superpowers/specs/2026-04-30-fxav-crew-pages-v1.md §4.3 admin-only tables.",
    `// Count: ${tables.length} tables.`,
    "export const ADMIN_TABLES: readonly string[] = [",
    rows,
    "] as const;",
    "",
  ].join("\n");
}

function main(): void {
  const spec = readFileSync(SPEC_PATH, "utf8");
  const tables = extractAdminTablesFromSpec(spec);
  writeFileSync(OUT_PATH, render(tables));
}

main();
