/**
 * scripts/generate-execution-methods.ts  (pnpm gen:execution-methods)
 *
 * Reads the installed postgres.js driver's type declarations and version, and
 * writes tests/db/__generated__/postgresExecutionMethods.ts -- the committed
 * derived core of the destructive-file analyzer's execution set (spec
 * docs/superpowers/specs/2026-08-16-execution-methods-driver-derived-design.md §2.2).
 *
 * Usage:
 *   pnpm gen:execution-methods          # write the generated module
 *   pnpm gen:execution-methods --check  # write nothing; exit 1 if it would change
 */
import { readFileSync, writeFileSync } from "node:fs";

import { deriveExecutionMethods } from "./execution-methods/lib";

export const DRIVER_TYPES_PATH = "node_modules/postgres/types/index.d.ts";
export const DRIVER_PACKAGE_JSON_PATH = "node_modules/postgres/package.json";
export const OUT_PATH = "tests/db/__generated__/postgresExecutionMethods.ts";

function render(): string {
  const pkg = JSON.parse(readFileSync(DRIVER_PACKAGE_JSON_PATH, "utf8")) as { version: string };
  const derived = deriveExecutionMethods(readFileSync(DRIVER_TYPES_PATH, "utf8"));
  return [
    "// @generated by scripts/generate-execution-methods.ts; do not edit. Regenerate: pnpm gen:execution-methods",
    `// Source: ${DRIVER_TYPES_PATH} (postgres ${pkg.version}).`,
    `export const POSTGRES_TYPES_VERSION = ${JSON.stringify(pkg.version)};`,
    `export const POSTGRES_EXECUTION_CORE: readonly string[] = ${JSON.stringify(derived.core)};`,
    `export const POSTGRES_PARAMETER_MEMBERS: readonly string[] = ${JSON.stringify(derived.parameterMembers)};`,
    "",
  ].join("\n");
}

const next = render();
if (process.argv.includes("--check")) {
  const current = readFileSync(OUT_PATH, "utf8");
  if (current !== next) {
    console.error(`${OUT_PATH} is stale; run pnpm gen:execution-methods`);
    process.exit(1);
  }
} else {
  writeFileSync(OUT_PATH, next);
}
