import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { extractWatermarkSymbolsFromSpec } from "./extract-watermark-symbols";

export const SPEC_PATH = "docs/superpowers/specs/2026-04-30-fxav-crew-pages-v1.md";
const PLAN_PATH = "docs/superpowers/plans/2026-04-30-fxav-crew-pages-v1/11-cross-cutting.md";
const WORKFLOW_PATH = ".github/workflows/x-audits.yml";
const OUT_PATH = "docs/superpowers/plans/coverage.md";

export type TraceabilityRow = {
  anchor: string;
  title: string;
  owningTasks: string[];
  status: "planned" | "implemented" | "deferred" | "intentionally out of scope" | "MISSING";
  evidence: string;
  notes: string;
};

export type TraceabilityMatrix = {
  rows: TraceabilityRow[];
  findings: string[];
  markdown: string;
};

function unique(values: readonly string[]): string[] {
  return Array.from(new Set(values));
}

function markdownTableCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

function extractHeadingAnchors(spec: string): TraceabilityRow[] {
  const rows: TraceabilityRow[] = [];
  for (const line of spec.split(/\r?\n/)) {
    const match = line.match(/^(#{1,4})\s+((\d+(?:\.\d+)*)\s+.+)$/);
    if (!match?.[2] || !match[3]) continue;
    rows.push({
      anchor: `§${match[3]}`,
      title: match[2].trim(),
      owningTasks: [],
      status: "implemented",
      evidence: "spec heading anchor",
      notes:
        "Heading anchors are walked for matrix completeness; structured coverage markers own normative-unit mapping.",
    });
  }
  return rows;
}

function extractSpecIdAnchors(spec: string): TraceabilityRow[] {
  return Array.from(spec.matchAll(/^\s*<!--\s*spec-id:\s*([^>]+?)\s*-->/gm), (match) => {
    const anchor = match[1]!.trim();
    return {
      anchor,
      title: anchor,
      owningTasks: [],
      status: "MISSING" as const,
      evidence: "",
      notes: "spec-id anchor",
    };
  });
}

function extractAcceptanceCriteria(spec: string): TraceabilityRow[] {
  const rows: TraceabilityRow[] = [];
  for (const match of spec.matchAll(
    /-\s+(?:\*\*)?(AC-[A-Z0-9.]+)(?:\*\*)?\s+(?:\*\*)?([^—\n]+?)(?:\*\*)?\s+—?\s*([^\n]*)/g,
  )) {
    rows.push({
      anchor: match[1]!,
      title: `${match[2]!.trim()} ${match[3] ?? ""}`.trim(),
      owningTasks: [],
      status: "implemented",
      evidence: "acceptance criterion row",
      notes:
        "Historical AC rows are represented in the matrix; X.6 parity assertions audit the cross-cutting AC body contracts.",
    });
  }
  return rows;
}

function taskBlocks(plan: string): Array<{ id: string; body: string }> {
  const matches = Array.from(plan.matchAll(/^### Task ([^:\n]+):[^\n]*$/gm));
  return matches.map((match, index) => {
    const start = match.index ?? 0;
    const end = matches[index + 1]?.index ?? plan.length;
    return { id: `Task ${match[1]!.trim()}`, body: plan.slice(start, end) };
  });
}

function coverageMarkers(body: string): string[] {
  const withoutFences = body.replace(/```[\s\S]*?```/g, "");
  return Array.from(withoutFences.matchAll(/^\s*<!--\s*coverage:\s*([\s\S]*?)\s*-->/gm), (match) =>
    match[1]!
      .split(",")
      .map((part) => part.trim())
      .filter(Boolean),
  ).flat();
}

export function generateTraceability({
  spec,
  plan,
}: {
  spec: string;
  plan: string;
}): TraceabilityMatrix {
  const rowMap = new Map<string, TraceabilityRow>();
  for (const row of [
    ...extractHeadingAnchors(spec),
    ...extractSpecIdAnchors(spec),
    ...extractAcceptanceCriteria(spec),
  ]) {
    rowMap.set(row.anchor, row);
  }
  if (!rowMap.has("§16") && spec.includes("§16")) {
    rowMap.set("§16", {
      anchor: "§16",
      title: "Secrets/env coverage",
      owningTasks: [],
      status: "MISSING",
      evidence: "",
      notes: "synthetic §16 anchor from spec cross-references",
    });
  }

  const findings: string[] = [];
  for (const block of taskBlocks(plan)) {
    for (const marker of coverageMarkers(block.body)) {
      if (marker === "deferred-v2" || marker === "out-of-scope") continue;
      const row = rowMap.get(marker);
      if (!row) {
        findings.push(`MISSING_ANCHOR:${marker}`);
        continue;
      }
      row.owningTasks.push(block.id);
      if (row.status === "MISSING") row.status = "planned";
    }
  }

  const rows = Array.from(rowMap.values()).sort((a, b) => a.anchor.localeCompare(b.anchor));
  const markdown = [
    "# Spec Coverage Matrix",
    "",
    "<!-- @generated by scripts/generate-traceability.ts; do not edit manually. -->",
    "",
    "| Spec anchor | Title | Owning task ID(s) | Status | Implementation evidence | Notes |",
    "| --- | --- | --- | --- | --- | --- |",
    ...rows.map((row) =>
      [
        row.anchor,
        markdownTableCell(row.title),
        row.owningTasks.join(", ") || "—",
        row.status,
        markdownTableCell(row.evidence || "—"),
        markdownTableCell(row.notes || "—"),
      ]
        .join(" | ")
        .replace(/^/, "| ")
        .replace(/$/, " |"),
    ),
    "",
    `Findings: ${findings.length === 0 ? "none" : findings.join(", ")}`,
    "",
  ].join("\n");

  return { rows, findings, markdown };
}

function readPlanCorpus(planPath: string): string {
  const dir = dirname(planPath);
  return readdirSync(dir)
    .filter((entry) => /^\d{2}-.+\.md$/.test(entry) || entry === "11-cross-cutting.md")
    .sort()
    .map((entry) => readFileSync(join(dir, entry), "utf8"))
    .join("\n\n");
}

function extractAdminTablesFromSpec(spec: string): string[] {
  const showsInternal = spec.match(/- \*\*`(shows_internal)`:\s*admin-only/);
  const adminLine = spec.split(/\r?\n/).find((line) => line.startsWith("- **Admin-only tables"));
  if (!showsInternal || !adminLine) throw new Error("Could not find §4.3 admin-only table prose");
  const tableDefinitions = new Set(
    Array.from(spec.matchAll(/create table ([a-z][a-z0-9_]*)/g), (match) => match[1]),
  );
  return unique([
    showsInternal[1]!,
    ...Array.from(adminLine.matchAll(/`([a-z][a-z0-9_]*)`/g), (match) => match[1]!),
  ]).filter((table) => table !== "shows" && tableDefinitions.has(table));
}

function extractPlanAdminTables(plan: string): string[] {
  const block = plan.match(/const ADMIN_BOOTSTRAP_NAMES = \[([\s\S]*?)\]\s+as const;/);
  if (!block?.[1]) return [];
  return Array.from(block[1].matchAll(/['"]([a-z][a-z0-9_]*)['"]/g), (match) => match[1]!);
}

function setDiff(prefix: string, expected: readonly string[], actual: readonly string[]): string[] {
  const actualSet = new Set(actual);
  return expected.filter((value) => !actualSet.has(value)).map((value) => `${prefix}:${value}`);
}

export function parseRequiredChecksFromSpec(spec: string): string[] {
  const acX6 = spec.match(/AC-X\.6[\s\S]*?### 17\.2\.1/);
  if (!acX6?.[0]) throw new Error("Could not find AC-X.6 body");
  return unique(
    Array.from(acX6[0].matchAll(/`([^`]+)`/g), (match) => match[1]!).filter((value) =>
      /^x[1-6]-|^traceability-audit$|^verify-branch-protection-status$/.test(value),
    ),
  );
}

export function loadRequiredChecksFromSpec(specPath = SPEC_PATH): string[] {
  return parseRequiredChecksFromSpec(readFileSync(specPath, "utf8"));
}

function expectedCheckFromAcBody(spec: string, ac: string): string | null {
  const escaped = ac.replace(".", "\\.");
  const body =
    spec.match(
      new RegExp(
        `(?:\\*\\*)?${escaped}(?:\\*\\*)?[\\s\\S]*?(?=\\n- (?:\\*\\*)?AC-|\\n### 17\\.2\\.1)`,
      ),
    )?.[0] ?? "";
  if (/traceability/i.test(body)) return "traceability-audit";
  if (/email canonicalization/i.test(body)) return "x5-email-canonicalization";
  if (/No global cursor/i.test(body)) return "x4-no-global-cursor";
  if (/auth-validation/i.test(body)) return "x3-trust-domain";
  if (/raw error codes/i.test(body)) return "x2-no-raw-codes";
  if (/orphan error codes|catalog/i.test(body)) return "x1-catalog-parity";
  return null;
}

export function parseAcRequiredCheckFindings(spec: string): string[] {
  const checks = parseRequiredChecksFromSpec(spec);
  const findings: string[] = [];
  const acRows = extractAcceptanceCriteria(spec)
    .map((row) => row.anchor)
    .filter((anchor) => /^AC-X\.\d+$/.test(anchor));
  for (const ac of acRows) {
    const expected = expectedCheckFromAcBody(spec, ac);
    if (!expected) continue;
    const prefix = ac === "AC-X.6" ? "traceability-audit" : expected.replace(/-\w+$/, "");
    const actual =
      checks.find((check) => check === expected || check.startsWith(prefix)) ??
      (ac === "AC-X.5" ? checks.find((check) => check.startsWith("x5-")) : undefined);
    if (actual && actual !== expected) {
      findings.push(`+ac_body_list_drift:${ac} expected=${expected} actual=${actual}`);
    }
  }
  return findings;
}

function parseJobBlock(workflow: string, job: string): string {
  const match = workflow.match(
    new RegExp(`\\n  ${job}:\\n([\\s\\S]*?)(?=\\n  [a-zA-Z0-9_-]+:\\n|\\s*$)`),
  );
  return match?.[1] ?? "";
}

export function parseWorkflowFindings(
  workflow: string,
  requiredChecks = loadRequiredChecksFromSpec(),
): string[] {
  const findings: string[] = [];
  if (workflow.includes("pull_request_target")) findings.push("+pull_request_target_used");
  if (!workflow.includes("schedule:") || !workflow.includes("0 9 * * 1"))
    findings.push("+missing_schedule");

  const auditJobs = requiredChecks.filter((check) => check !== "verify-branch-protection-status");
  for (const job of auditJobs) {
    const block = parseJobBlock(workflow, job);
    if (!block) {
      findings.push(`+missing_job:${job}`);
      continue;
    }
    if (!/if:\s*github\.event_name != 'schedule'/.test(block))
      findings.push(`+missing_schedule_guard:${job}`);
    if (!block.includes("Verify generated admin tables file is fresh"))
      findings.push(`+missing_freshness_step:${job}`);
    if (!block.includes("pnpm gen:admin-tables")) findings.push(`+missing_admin_generator:${job}`);
  }

  const privileged = parseJobBlock(workflow, "verify-branch-protection");
  if (!privileged) findings.push("+missing_job:verify-branch-protection");
  const privilegedDeferred = privileged ? /^\s*if:\s*false\b/m.test(privileged) : false;
  if (
    privileged &&
    !privilegedDeferred &&
    !privileged.includes("github.event_name == 'push' || github.event_name == 'schedule'")
  ) {
    findings.push("+privileged_job_bad_if");
  }

  const reader = parseJobBlock(workflow, "verify-branch-protection-status");
  if (!reader) findings.push("+missing_job:verify-branch-protection-status");
  const readerDeferred = reader ? /^\s*if:\s*false\b/m.test(reader) : false;
  if (reader && !readerDeferred) {
    for (const match of reader.matchAll(/([A-Z_]+):\s*\$\{\{\s*secrets\./g)) {
      findings.push(`+reader_uses_secret:${match[1]}`);
    }
    if (!reader.includes("GH_TOKEN: ${{ github.token }}"))
      findings.push("+reader_missing_github_token");
    if (!reader.includes("8 * 24 * 60 * 60")) findings.push("+reader_missing_8_day_window");
  }
  return findings;
}

function watermarkParityFindings(spec: string, plan: string): string[] {
  const specSymbols = extractWatermarkSymbolsFromSpec(spec);
  const planSymbols = extractPlanWatermarkSymbols(plan);
  return [
    ...setDiff(
      "+missing_authoritative_in_plan",
      specSymbols.authoritativeGatingWatermarks,
      planSymbols.authoritativeGatingWatermarks,
    ),
    ...setDiff(
      "-extra_authoritative_in_plan",
      planSymbols.authoritativeGatingWatermarks,
      specSymbols.authoritativeGatingWatermarks,
    ),
    ...setDiff(
      "+missing_display_only_in_plan",
      specSymbols.displayOnlyTimestamps,
      planSymbols.displayOnlyTimestamps,
    ),
    ...setDiff(
      "-extra_display_only_in_plan",
      planSymbols.displayOnlyTimestamps,
      specSymbols.displayOnlyTimestamps,
    ),
  ];
}

function collectPlanSet(plan: string, name: string): string[] {
  const match = plan.match(
    new RegExp(`const\\s+${name}\\s*=\\s*new\\s+Set\\(\\[([\\s\\S]*?)\\]\\);`),
  );
  if (!match?.[1]) throw new Error(`Could not find ${name} in plan`);
  return unique(Array.from(match[1].matchAll(/"([^"]+)"/g), (entry) => entry[1]!));
}

function extractPlanWatermarkSymbols(
  plan: string,
): ReturnType<typeof extractWatermarkSymbolsFromSpec> {
  return {
    authoritativeGatingWatermarks: collectPlanSet(plan, "AUTHORITATIVE_GATING_WATERMARKS"),
    displayOnlyTimestamps: collectPlanSet(plan, "DISPLAY_ONLY_TIMESTAMPS"),
    syncEntryPoints: [],
    bannedCombos: [],
  };
}

export function auditTraceability({
  specPath = SPEC_PATH,
  planPath = PLAN_PATH,
  workflowPath = WORKFLOW_PATH,
}: {
  specPath?: string;
  planPath?: string;
  workflowPath?: string;
} = {}): string[] {
  const spec = readFileSync(specPath, "utf8");
  const plan = readPlanCorpus(planPath);
  const workflow = existsSync(workflowPath) ? readFileSync(workflowPath, "utf8") : "";
  const matrix = generateTraceability({ spec, plan });
  const findings = [...matrix.findings];

  for (const row of matrix.rows) {
    if (row.status === "MISSING" && row.notes !== "acceptance criterion")
      findings.push(`+missing_coverage:${row.anchor}`);
  }

  const specAdminTables = extractAdminTablesFromSpec(spec);
  const planAdminTables = extractPlanAdminTables(plan);
  findings.push(...setDiff("+missing_in_ac25", specAdminTables, planAdminTables));
  findings.push(...setDiff("-extra_in_ac25", planAdminTables, specAdminTables));

  findings.push(...watermarkParityFindings(spec, plan));
  findings.push(...parseAcRequiredCheckFindings(spec));
  findings.push(...parseWorkflowFindings(workflow, parseRequiredChecksFromSpec(spec)));
  return unique(findings);
}

function main(): void {
  const spec = readFileSync(SPEC_PATH, "utf8");
  const plan = readPlanCorpus(PLAN_PATH);
  const matrix = generateTraceability({ spec, plan });
  mkdirSync(dirname(OUT_PATH), { recursive: true });
  writeFileSync(OUT_PATH, matrix.markdown);
  const findings = auditTraceability();
  if (findings.length > 0) {
    for (const finding of findings) console.error(finding);
    process.exitCode = 1;
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
